.github/workflows/docker-release.yaml
Very basic build and push (only tagging "latest").  This will build and push a new docker image on each merge to `main`.
References:
- [docker-login action](https://github.com/marketplace/actions/docker-login)
- [docker build and push action](https://github.com/marketplace/actions/build-and-push-docker-images)
=> Minimum viable docker image build and push

Makefile, README.md, helm/ingress-controller/templates/controller-deployment.yaml, helm/ingress-controller/values.yaml
* Update the default image repository name to be what we want (once its public)
* Handle if pod annotations aren't set
=> minor helm clean up items so its useable

.github/workflows/release.yaml
Created `helm_bump_version` job to automate patch-level version bumping of helm chart
=> Automating semver PATCH bump of helm chart

cmd/manager/main.go, internal/controllers/ingress_controller.go, internal/controllers/tunnel_controller.go, pkg/agentapiclient/tunnel.go, pkg/ngrokapidriver/driver.go, pkg/ngrokapidriver/types.go
This makes the following changes:
1. Switches to cobra, which is better than the goflags package
2. Removes some refs/derefs which felt unidiomatic. Generally, `*x` shouldn't happen very often, and so I pretty much shuffled around types to make that less common.
3. Updates domain list iteration to be more idiomatic
4. Other misc stuff I'm sure
I've commented on most of the changes below to indicate why they're there.
=> Make assorted changes to make code more idiomatic

README.md
It looks like the chart name is `ngrok-ingress-controller`. Updating the documentation to match.
```sh
$ helm search repo ngrok
NAME                          	CHART VERSION	APP VERSION	DESCRIPTION                                       
ngrok/ngrok-ingress-controller	0.1.2        	0.1.0      	A Kubernetes ingress controller built using ngrok.
```
=> Update helm install docs

.github/workflows/docker.yaml, .github/workflows/helm_release.yaml
This makes it so the release actions don't run on pushes to main for forks.
=> Selectively run actions on fork

.github/ISSUE_TEMPLATE/controller_bug_report.yaml, .github/ISSUE_TEMPLATE/feature_request.yaml, .github/ISSUE_TEMPLATE/helm_bug_report.yaml, .github/PULL_REQUEST_TEMPLATE.md, README.md, helm/ingress-controller/README.md, internal/controllers/ingress_controller.go, internal/controllers/main.go, internal/controllers/tunnel_controller.go, pkg/ngrokapidriver/driver.go
Add Issue and Pull Request Templates
Will help us better triage issues by providing community members and ourselves templates for creating issues. We can still fall back to "Blank" issues if we need to.
=> Add Issue and Pull Request Templates

.github/ISSUE_TEMPLATE/controller_bug_report.yaml, .github/ISSUE_TEMPLATE/helm_bug_report.yaml
Fixes 2 of the issue templates that aren't valid because they are missing a `description`.
=> fix: Add description to issue templates so they are valid

go.mod, internal/controllers/ingress_controller.go, internal/controllers/ingress_controller_test.go, internal/controllers/tunnel_controller.go, internal/controllers/tunnel_controller_test.go
Related: #39 
This change adds in some tests for both the ingress controller and tunnel controller to validate the edge and tunnel API objects we are creating.
Test that given certain ingress objects, they return the respective edge and tunnel API objects.
=> Add unit tests for ingress controller & tunnel controller

helm/ingress-controller/templates/controller-deployment.yaml, internal/controllers/ingress_controller.go, internal/controllers/tunnel_controller.go
- Implemented two predicate filters per reconciler
- Enabled prometheus scraping
1. Ignores Ingress delete events as we leverage a finalizer and handle delete operations when the `metadata.deletionTimestamp` is applied to the object
2. Ignores update events with no changes to the Ingress object's Spec (no new revision)
3. Added prometheus scraping to the helm chart, which helped visualize reconciliation events
This change is leveraging predicate filters to avoid taking action when no action is necessary.
These two blog posts talk about this:
1. [Using Event Filters with Kubebuilder - Part 1](https://stuartleeks.com/posts/kubebuilder-event-filters-part-1-delete/)
1. [Using Event Filters with Kubebuilder - Part …
=> Implemented two predicate filters per reconciler

.github/workflows/pr-comments.yaml
Related: #60 
Fixes PR comments not working as seen in #78.
Due to how `GITHUB_TOKEN` permissions are scoped for pull_requests, we need to check this in first and run it with the `pull_request_target` event type so that it can comment on PRs
No
=> Fix for pr-commenting

internal/controllers/ingress_controller.go, internal/controllers/predicate_filters.go, internal/controllers/tunnel_controller.go
Updates predicate filters so we also capture changes to annotations
Annotations are outside of the `Ingress`'s `spec` field so they don't trigger a change in the generation. This compares the old annotations to the new annotations to figure out if we need to do a reconcile.
No
=> Trigger update when annotations change

.github/workflows/docker.yaml, Makefile, README.md, cmd/manager/main.go, helm/ingress-controller/CHANGELOG.md, helm/ingress-controller/Chart.yaml, helm/ingress-controller/README.md, helm/ingress-controller/templates/_helpers.tpl, helm/ingress-controller/templates/agent-config-cm.yaml, helm/ingress-controller/templates/controller-cm.yaml, helm/ingress-controller/templates/controller-deployment.yaml, helm/ingress-controller/templates/controller-rbac.yaml, helm/ingress-controller/templates/controller-serviceaccount.yaml, helm/ingress-controller/templates/ingress-class.yaml, helm/ingress-controller/tests/__snapshot__/agent-config-cm_test.yaml.snap, helm/ingress-controller/tests/__snapshot__/controller-cm_test.yaml.snap, helm/ingress-controller/tests/__snapshot__/controller-deployment_test.yaml.snap, helm/ingress-controller/tests/__snapshot__/controller-rbac_test.yaml.snap, helm/ingress-controller/tests/__snapshot__/controller-serviceaccount_test.yaml.snap, helm/ingress-controller/tests/__snapshot__/credentials-secret_test.yaml.snap, helm/ingress-controller/tests/__snapshot__/ingress-class_test.yaml.snap, helm/ingress-controller/tests/agent-config-cm_test.yaml, helm/ingress-controller/tests/controller-cm_test.yaml, helm/ingress-controller/tests/controller-deployment_test.yaml, helm/ingress-controller/tests/controller-rbac_test.yaml, helm/ingress-controller/tests/controller-serviceaccount_test.yaml, helm/ingress-controller/tests/credentials-secret_test.yaml, helm/ingress-controller/tests/ingress-class_test.yaml, helm/ingress-controller/values.yaml
Resolves: #55 
Adding more helm common values like overriding the `image.registry` and adding `image.pullSecrets`. See changes in the `values.yaml` file.
* Added additional helm template snapshots for future testing. About half of this PR are tests.
* Updated the command line args of the controller to support taking an `election-id` since we support overriding the name now that is used to prefix resources.
Yes, specifically the names of resources are now prefixed to support overriding with `nameOverride` and `fullnameOverride` as is common in a lot of helm charts.
=> Add Helm Common Values

helm/ingress-controller/templates/NOTES.txt
Selecting first service (other than "kubernetes") that is listening on 80 or 443 and generating a basic Ingress object manifest
related: #63
Providing a ready-to-go example `Ingress` manifest so that new users can easily start to leverage the ingress controller, right after installation.
The template now queries all K8s Services (across all namespaces) and selects the first Service that is listening on either 80 or 443 (that is not the "kubernetes" API service).  Then it generates an `Ingress` manifests, from the selected service. 
No
=> Added example Ingress manifest to NOTES.txt

internal/controllers/domain_controller.go, main.go
Moves the client initialization to main.go so we only have to set the user-agent in 1 place and treat it like regular dependency injection.
Pass in the required client with Dependency injection
No
=> Move client initialization to main.go

go.mod, helm/ingress-controller/templates/rbac/role.yaml, helm/ingress-controller/tests/__snapshot__/controller-deployment_test.yaml.snap, internal/controllers/tcpedge_controller.go, internal/controllers/utils.go, internal/ngrokapi/clientset.go, main.go
Add initial `TCPEdge` controller implementation for reconciling `TCPEdges`. Also add a ngrok API Clientset to make it easier to configure all of the clients and reference them in an easy way.
While not directly exposed via the ingress controller, this allows for basic setup of TCP Edges backed by a labeled tunnel group like so
```yaml
---
kind: TCPEdge
apiVersion: ingress.k8s.ngrok.com/v1alpha1
metadata:
name: starwars-edge
namespace: default
spec:
backend:
labels:
k8s.ngrok.com/namespace: default
k8s.ngrok.com/service: starwars
k8s.ngrok.com/port: "23"
---
kind: Tunnel
apiVersion: ingress.k8s.ngrok.com/v1alpha1
metadata:
name: starwars-tunnel
namespace: default
spec:
forwardsTo: starwars.default.svc.cluster.local:23
labels:
k8s.ngrok.com/namespace: default
k8s.ngrok.com/service: starwars …
```
=> Add TCPEdge Controller

internal/controllers/httpsedge_controller.go
Currently when applying, on the first reconcile, the controller panics. This resolves that panic.
```
2023-01-16T22:32:16Z	INFO	controllers.ingress	Updating Ingress status with load balancer ingress statuses
2023-01-16T22:32:17Z	INFO	controllers.https-edge	Creating new route	{"edgeID": "edghts_2KQYaOhlv5WehA4UbTTOnWqo56F", "match": "/", "matchType": "path_prefix", "backendID": "bkdtg_2KC6P5MVwn6KenkRAc1PbBnr9Ph"}
2023-01-16T22:32:17Z	INFO	Observed a panic in reconciler: runtime error: index out of range [0] with length 0	{"controller": "httpsedge", "controllerGroup": "ingress.k8s.ngrok.com", "controllerKind": "HTTPSEdge", "HTTPSEdge": {"name":"minimal-ingress","namespace":"ngrok-ingress-controller"}, "namespace": "ngrok-ingress-controller", "name": "minimal-ingress", "reconcileID": …
```
=> Use the edge spec routes instead of remoteEdge routes

internal/controllers/httpsedge_controller.go
Fixes creating tunnel group backends for if none have matching labels. Currently it keeps creating empty tunnel group backends with no selectors.
Fix not passing labels to creating tunnel group backend
No
=> Fix for finding or creating tunnel group backends

helm/ingress-controller/README.md, helm/ingress-controller/tests/__snapshot__/ingress-class_test.yaml.snap, helm/ingress-controller/values.yaml, scripts/e2e.sh
Changes the default helm values for whether the ngrok ingress class should be the default from true to false. We should not assume we would be the default as it could cause problems if someone installs it in a cluster with another ingress controller.
Change the value in the values.yaml file
Technically yes, this is non-passive and reverses the behavior. If its installed in a cluster and its the only ingress class though, it will not pickup things by default anymore.
Our logic for how ingress classes are handled is here https://github.com/ngrok/kubernetes-ingress-controller/blob/main/internal/controllers/main.go#L29-L37 . With these helm defaults, you would install it in the cluster and would need to specify the ingress class on their ingress objects. Alternatively, if we set the default …
=> Set ingress class default to false

internal/controllers/tcpedge_controller.go, internal/ngrokapi/clientset.go, internal/ngrokapi/clientset_test.go, main.go
This fixes some issues in the TCPEdge Controller. Mainly it would not automatically provision a TCP address and attach it to the edge and you had to manually do this. Now it will reserve a TCP Address and attach it to the edge.
Checks to see if an existing TCP Address with matching metadata already exists and if so, will use that. Otherwise, it will create a new one and attach it to the Edge
No
=> Tcp edge fixes

docs/annotations.md
As we start to add more Edge Route Modules, this provides a place that we can list all of the ingress annotations, their purpose, defaults, and how to use them for now. I imagine we'll have a docs site eventually, but for now, this at least documents the spec of how they should work.
No
=> Document Ingress annotations

internal/controllers/httpsedge_controller.go, internal/controllers/tcpedge_controller.go, internal/ngrokapi/clientset.go, internal/ngrokapi/clientset_test.go, internal/ngrokapi/edge_modules_clientset.go, internal/ngrokapi/edge_modules_https.go, internal/ngrokapi/edge_modules_tcp_clientset.go, internal/ngrokapi/edge_modules_tls_clientset.go, main.go
The HTTPSEdgeRoute update API does not support fully removing route modules. When we reconcile HTTPSEdgeRoutes, if a route module is removed from the spec, we need to delete it. The only way to do that is through the HTTPSEdgeRouteModules API, so we will need clients for that. This will allow us to pass the `ngrokapi.Clientset` into various controllers that require complex logic that spans many different API clients from `ngrok-api-go`. This should clean up dependency injection as we start adding more route modules.
Add nested clientsets to the ngrok API clientset. We will start consuming these in subsequent PRs.
No
=> Add nested Clientsets for manipulating Route Modules

internal/controllers/httpsedge_controller.go
Fixes #123
When an Edge route selector is modified, it creates a new route, but the old one is not cleaned up. This fixes a bug where old edge routes are not cleaned up
After we create/update the existing routes, delete any routes that are not in the new set of routes before syncing the status.
No
=> Remove routes that are no longer in the spec.

api/v1alpha1/domain_types.go, internal/controllers/domain_controller.go
On startup, the controller gets events for every object it watches. This includes domains. So whenever a controller pod starts it lists out all the domains with worthless updates that trigger more reconcile loops. 
The domain object isn't large, this checks if any fields are actually different before making an update call 
No
=> Only apply an update to the domain if its actually different

.github/workflows/ci.yaml, Dockerfile, README.md, go.mod, scripts/preflight.sh
Updates go to the latest version `1.20`.
Update everywhere we set the go version to `1.20`
No
=> Bump go version to 1.20

internal/controllers/httpsedge_controller.go, internal/controllers/utils.go
Fixes #150 
Right now we always either delete the route modules or update them regardless of if there are changes. This results in making unnecessary API calls. Since we get the route back after issuing a create/update, we can just check to see if there are any updates that need to happen before we do the update
I refactored this so there is an `edgeRouteModuleUpdater` that we can call for each route. While moving the existing methods over to the `edgeRouteModuleUpdate`, I added checks so that we make API requests if we need to. This helps to clean things up ahead of working on #132.
No
=> Refactor route module updates to be lazy

helm/ingress-controller/CHANGELOG.md, helm/ingress-controller/Chart.yaml, helm/ingress-controller/README.md, helm/ingress-controller/templates/_helpers.tpl, helm/ingress-controller/tests/__snapshot__/controller-deployment_test.yaml.snap, helm/ingress-controller/tests/__snapshot__/controller-serviceaccount_test.yaml.snap, helm/ingress-controller/tests/__snapshot__/ingress-class_test.yaml.snap, helm/ingress-controller/values.yaml
If you follow the helm install instructions, it will install the most recent helm release `0.6.0` which defaults the docker image tag to `latest`. This causes issues since the helm chart does not have the CRDs that we recently added. For deterministic installs, we should default to using the `appVersion` in the `Chart.yaml` if  `image.tag` is not supplied.
Change default `image.tag` from `latest` to `.Chart.AppVersion`
No
=> Use Chart appVersion if tag is not specified

helm/ingress-controller/CHANGELOG.md, helm/ingress-controller/Chart.yaml, helm/ingress-controller/tests/__snapshot__/controller-deployment_test.yaml.snap, helm/ingress-controller/tests/__snapshot__/controller-serviceaccount_test.yaml.snap, helm/ingress-controller/tests/__snapshot__/ingress-class_test.yaml.snap
Cut new release of the helm chart.
:warning: Yes. The annotation system for configuring Ingresses has been substantially changed since 0.4.0 to use `NgrokModuleSet` Custom Resources instead of individual annotations.
=> Bump Helm Chart version to 0.7.0

.dockerignore, Dockerfile, Makefile, internal/version/version.go, main.go
Resolves #188 
Includes the ingress controller version in the `useragent` string. Also prints out the build info when the controller starts.
Pass build info variables to the linker when building the go binary.  Had to change the `.dockerignore` in order to get the `.git` directory, `VERSION`, `Makefile`, and a few others into the docker context so they could be added in the image during the build.
No
=> Include ngrok controller version in user agent

Makefile, go.mod, helm/ingress-controller/README.md, helm/ingress-controller/templates/controller-deployment.yaml, helm/ingress-controller/tests/__snapshot__/controller-deployment_test.yaml.snap, helm/ingress-controller/tests/controller-deployment_test.yaml, helm/ingress-controller/values.yaml, main.go
resolves: #144 
Allows configuring the controller log levels via helm chart values.
Removes the default set in `main.go` of being in `development` mode, back to `zap` defaults. Adds new config values to the helm chart's `values.yaml` for setting different log configuration values.
For development, setting the following overrides should provide the same log behavior as before.
```yaml
log:
format: console
level: debug
stacktraceLevel: panic
```
Yes, to default log level and output.
=> Add log level configuration to helm chart

Makefile
Make deploy has 2 problems right now:
- I left the debug flag on in a commit and it dumps a wall of yaml that's annoying as the default
- with the latest image tag changes, it gets an image pull backoff error
- remove the debug flag
- set tag to latest since thats what the make file builds
=> Clean up make deploy command

docs/README.md
the ingress controller uses the ingress class stable version spec `ingressClassName` and not the old annotation syntax
=> Fix docs ingress

README.md, docs/developer-guide/releasing.md, helm/ingress-controller/templates/NOTES.txt
This change removes the comment about this project being in alpha from the notes section. It also removes the note about a pro account since it is no longer required.
Removing the incorrect text
No
=> fix: remove note about alpha and pro account

docs/examples/hello-world/manifests.yaml
This makes the manifest.yaml applicable with environment variables and the 
Example:
```bash
export SUBDOMAIN="subdomain-name"
wget https://raw.githubusercontent.com/sudobinbash/kubernetes-ingress-controller/frederico/get-started-tweak/docs/examples/hello-world/manifests.yaml -O - | envsubst | kubectl apply -f -
```
This will replace `${SUBDOMAIN}.ngrok.io` with `subdomain-name.ngrok.io`
=> Make subdomain replaceable with env variable

helm/ingress-controller/templates/rbac/role.yaml, helm/ingress-controller/tests/__snapshot__/controller-deployment_test.yaml.snap, internal/controllers/ingress_controller.go, internal/store/cachestores.go, internal/store/driver.go, internal/store/store.go, internal/store/store_test.go, internal/store/testutility.go
Closes #220 
Fixes backend ports specified by `name` in Ingress Backend Service definitions not working and defaulting to `0`. You can now specify the port by `name` as one would expect. Ex:
```yaml
spec:
ingressClassName: ngrok
rules:
- host: my-test-app-1.ngrok.io
http:
paths:
- path: /
pathType: Prefix
backend:
service:
name: test-app-1
port:
name: http # Fixed this not working
```
* Added support for `v1.Service` to the cachestore and driver
* Initially seed the driver's store with `v1.Service`s on start
* Modified the permissions of the controller to `get/list/watch` `v1.Service`
* Check if the port number on the ingress rule's backend service is `<= 0`. If it is, then we look up the service by its name and try to find a port with a matching name and use the port defined on it.
No
=> fix: Add support for named service ports in Ingress Backend Services

helm/ingress-controller/CHANGELOG.md, helm/ingress-controller/Chart.yaml, helm/ingress-controller/tests/__snapshot__/controller-deployment_test.yaml.snap, helm/ingress-controller/tests/__snapshot__/controller-serviceaccount_test.yaml.snap, helm/ingress-controller/tests/__snapshot__/ingress-class_test.yaml.snap
Releases version `0.9.0` of the helm-chart. Defaults the controller image version to `0.7.0`
No
=> :tada: Cut Helm chart 0.9.0 release :tada:

docs/developer-guide/README.md, e2e-fixtures/hello-world-ingress/EXAMPLE-config-pt2.yaml, e2e-fixtures/hello-world-ingress/hello-world-ingress.yaml, e2e-fixtures/hello-world-ingress/kustomization.yaml, e2e-fixtures/ingress-class/e2e-expected.yaml, flake.nix, helm/ingress-controller/README.md, scripts/e2e.sh
Changes that made the e2e tests work for me, these may not be universally applicable, so happy to cherry pick anything that is actually useful.
- Typo in developer guide
- Kustomization changes in `e2e-fixtures/hello-world-ingress` to remove `bezek-hello-world-ingress-2` and set via config
- `e2e-fixtures/ingress-class` 404 is HTTP/2 for me
- The secrets keys don't seem to have `NGROK` prefix, unlike the environment variables they set
- `jq` and `yq` weren't installed on this machine, added to nix config, and added some bash to check for them up front. looks like josh is adding nix support though, so this may become irrelevant.
- Changed the test for `GOOGLE_CLIENT_ID` to not error out if not defined, due to the `set -eu -o pipefail`
- A message before the long sleep to make the lack of …
=> Some updates to handle different cases for e2e run

internal/controllers/httpsedge_controller.go, internal/controllers/utils.go
Fixes: #233 
When the `iprestriction` points to a policy that doesn't exist, we still create the edge, but leave it widely open.
Pre-validate the names. Ignore names that look like ip policy ids (e.g. prefixed with `ipp_`)
The now invalid configs no longer result in an edge route.
=> validate ip restriction rules, before creating the route

helm/ingress-controller/templates/credentials-secret.yaml, helm/ingress-controller/tests/__snapshot__/credentials-secret_test.yaml.snap, helm/ingress-controller/tests/credentials-secret_test.yaml
When one generates the manifests with `helm template`, you will notice that the resulting manifest to create the secret credentials is missing the `metadata.namespace` key/value.  This is not a problem when one generates the manifests for use in the `default` namespace.  However, the problem shows itself if the goal is to use a namespace other than `default`.
Adds `namespace` to the `credentials-secret.yaml` template.
No.
=> Add namespace to secret

README.md, internal/controllers/httpsedge_controller.go, internal/errors/errors.go
Resolves #208
Applying edge routes' backend is now deferred until after route modules are successfully applied. If route modules fail to apply for any reason, the route's backend remains unset, thus closing off access to the edge from that route.
This approach was inspired by [Niji's comment](https://github.com/ngrok/kubernetes-ingress-controller/issues/208#issuecomment-1553703178) in the parent issue.
1. Omit backend from new routes / Remove backend from current routes
2. Route modules now try to apply
2a. If route module application was successful, routes are then updated with their specified backend
2b. If unsuccessful, `reconcileRoutes` returns an error and the route remains backend-less
3. Route statuses are updated
Edge routes will no longer be valid if an error occurs while …
=> Initialize route backends after module updates

Makefile
Running `make` second time (after cleaning `.direnv/` directory) results in the following error:
Error: err: exit status 1: stderr: go: cannot load module listed in go.work file: open ~/kubernetes-ingress-controller/.direnv/go/pkg/mod/golang.ngrok.com/ngrok@v1.0.1-0.20230502190252-9115810884ac/examples/go.mod: no such file or directory
Since we actually moved `$GOPATH` to `./direnv/go` in the previous PR, now the controller gen sees many more things than we intend it to. Restrict it to only things we care about.
None
=> restrict generate to only our paths (not the whole `.direnv/go`)

.github/workflows/helm_release.yaml
* Updates the chart-release-action version
* Skips creating a release if it already exists
* Bump the GH Action version
* set `CR_SKIP_EXISTING: "true"`
No
=> Skip releasing chart if the release already exists

api/v1alpha1/ippolicy_types.go, helm/ingress-controller/templates/crds/ingress.k8s.ngrok.com_ippolicies.yaml, internal/controllers/ippolicy_controller.go, internal/controllers/ippolicy_controllers_test.go
Contributes to #221 
Since CIDR has to be unique within an IPPolicy: `HTTP 400: IP Policy Rule with CIDR '127.0.0.1/32' already exists [ERR_NGROK_1408]`, we need to calculate the diff and apply the changes in a safe way.
Use the following diffing logic to apply creates, deletes, and updates in the following order:
1. Create all new deny rules that don't exist in the remote with a matching CIDR.
2. Delete any allow rules with matching CIDRs that will be changing to deny rules. Then create the deny rules
3. Delete any deny rules with matching CIDRs that will be changing to allow rules. Then create the allow rules.
4. Create all new allow rules that don't exist in the remote with a matching CIDR.
5. Delete any remaining rules that are not in the spec.
6. Update any rules that exist in the …
=> Handle IPPolicy CRD state transitions in a safer way

internal/controllers/httpsedge_controller.go
Contributes to #221 
Updates the logic for matching routes in the spec to existing routes.
Since ngrok routes are unique by Match(Path in the Ingress Spec), we need to remove the check on MatchType(PathType), so they can be updated.
No
=> fix: for changing pathType between 'Exact' and 'Prefix'

internal/controllers/httpsedge_controller.go
Improve logging for the `httpsedge` controller.
* Clean up duplicated log values by by making a new logger using `WithValues`
* Pass loggers through the code using contexts
* Change some of the plain `.Info` logs to log at different verbosities. Ex: `log.V(1).Info` to effectively log at the `debug` level.
No
=> Improve logging for httpsedge controller

helm/ingress-controller/CHANGELOG.md, helm/ingress-controller/Chart.yaml, helm/ingress-controller/tests/__snapshot__/controller-deployment_test.yaml.snap, helm/ingress-controller/tests/__snapshot__/controller-pdb_test.yaml.snap, helm/ingress-controller/tests/__snapshot__/controller-serviceaccount_test.yaml.snap, helm/ingress-controller/tests/__snapshot__/ingress-class_test.yaml.snap
Creates a release candidate of the helm chart for testing purposes
* Updating the `CHANGELOG` with the changes that will be in the RC but are unreleased.
* Change the version of the helm chart to specify a RC. Since it doesn't follow semver, it won't appear in `helm search repo ngrok` unless we add the `--devel` flag
No
=> Helm chart Release candidate 0.11.0-rc.1

helm/ingress-controller/Chart.lock
Bump the version of the `bitnami/common` helm chart
Updates the `Chart.lock` with new version
No
=> Update chart dependency bitnami/common

internal/store/driver.go
These break statements shouldn't be here. They are breaking the out of the outer loop and are likely causing some of the desired domains, tunnels, edges not being created as fast as they could be. Luckily, they'll be caught in the next sync loop since they will exist and follow the update flow and the inner for loop will be broken, moving onto the next one
Remove the unnecessary break statements which cause reconciliation to take longer
No
=> fix: Remove unnecessary break in sync create/update loops

Dockerfile
Use the fancy buildkit --mount option to cache the /go directory between
builds.
=> add caching to docker build

internal/store/driver.go, internal/store/driver_test.go, scripts/migrate-edges.sh, scripts/migrate-tunnels.sh
closes: #267
related: #285
Similar to tunnels, any https edges that are not created by the ingress controller are deleted. Update the ingress controller to only look at things it created and ignore anything else, allowing the operator to define custom https edges.
Largely the same as with #285, but without defining any ownership references (since the https edges are unique within the cluster)
The currently existing edges are abandoned and the controller will try to crate new ones under its control. 
If downtime can be tolerated, the operator should just delete the old edges (via `kubectl delete httpsedges.ingress.k8s.ngrok.com --selector '!k8s.ngrok.com/controller-name' --all-namespaces`) before deploying the new version of the controller.
Alternatively, to adopt the edges in the …
=> Ingress controller owns https edges it creates and doesn't delete the ones it doesn't own.

api/v1alpha1/ngrok_common.go, internal/controllers/base_controller.go, internal/controllers/domain_controller.go, internal/controllers/httpsedge_controller.go, internal/controllers/ingress_controller.go, internal/controllers/ippolicy_controller.go, internal/controllers/tcpedge_controller.go, internal/controllers/tunnel_controller.go, internal/controllers/utils.go, internal/errors/errors.go
closes: #283 
Currently, the controllers don't (most of them) inspect the errors coming from the ngrok API and retry forever. With this PR, we'll look at the resulting error, and retry based on the error codes coming from the ngrok API:
* server errors will be retried
* rate limit errors will be retried with 1m backoff
* controller specific errors are retried depending on the controller. Only the `HTTPSEdge` controller is currently retrying, specifically for the case where the domain for this edge wasn't found (which allows the domain controller to register it concurrently) 
* extract common controller functionality into the `baseController`
* the `baseController` provides standardized error checking that can be customized by the concrete controller.
None
=> unified reconciling and error handling

Makefile
I keep running 'make deploy' without having these set, and then have to remember to set them.
It seems nicer to the developer to error out early.
=> Check for secret's env vars in 'make deploy'

api/v1alpha1/httpsedge_types.go, internal/controllers/httpsedge_controller.go, internal/controllers/tcpedge_controller.go, internal/store/driver.go, pkg/tunneldriver/driver.go
We have generics, we can do faster and better equality comparing in a few places.
These should be functionality identical. This is meant to be a rote refactor that the type-system covers, and no additional validation beyond that was done.
=> *: reflect.DeepEqual -> maps/slices.Equal

.github/workflows/ci.yaml, Makefile
We introduced a change that requires `NGROK_AUTHTOKEN` and `NGROK_API_KEY` vars to be set on deploy, which is useful when doing manual deploys. However, in CI we use the same, but just to see if we can deploy successfully, without actually using the values for these vars. In this case, the ci build fails, since it checks these vars as part of the `make deploy` run.
Split `deploy` cmd/script to two parts, and use the one that doesn't check in CI.
None
=> do no check env in CI

Makefile, internal/controllers/ingress_controller.go, internal/controllers/moduleset_controller.go, internal/store/driver.go, internal/store/driver_test.go, internal/store/updatestorehandler.go, main.go
closes: #287
Currently, the controller watches for changes in `NgrokModuleSet` CRs (and persists the updates), but it is not actively triggering reconciliation when they change. This means that changes only in modules are not applied to the `HTTPSEdge` CRs when the `NgrokModuleSet` CRs referenced by an `Ingress` get changed.
Once this PR merges, both `Ingress` and `NgrokModuleSet` will trigger reconciliation and will keep dependent objects up to date.
* Add another controller that owns and watches `NgrokModuleSet`s
* Trigger partial reconciliation, since only `HTTPSEdges` are affected by modules
* Make sure we are not doing too many changes, since both `Sync` methods might run concurrently
None
=> Reconciling ngrok-module-set changes

helm/ingress-controller/Chart.lock, internal/store/driver.go
related: #291 
With #293 we introduced a change that allow controllers deployed to multiple clusters to correctly identify https edges and tunnel (think of multiple devs running the same app in k8s on their own machines). However, because we used the ingress UID, we broke the case where the same service is used in multiple ingresses in the same namespace - essentially one of them will set the tunnel labels to its own and the rest will be un-routable. Here, we move to use a different identifier, e.g. service UID, with the premise that these are uniquely *enough* (both across the cluster and between clusters).
Extract the service UID and use it to set the https edge/tunnel labels.
None
=> Use service UID instead of ingress UID for tunnel labels

pkg/tunneldriver/driver.go
When forwarding TLS connection, we are setting the `ServerName`/SNI to the target. According to RFC 6066:
```
"HostName" contains the fully qualified DNS hostname of the server,
as understood by the client.  The hostname is represented as a byte
string using ASCII encoding without a trailing dot.  This allows the
support of internationalized domain names through the use of A-labels
defined in [RFC5890].  DNS hostnames are case-insensitive.  The
algorithm to compare hostnames is described in [RFC5890], Section
2.3.2.4.
```
However, our target is in the form `cluster-service-name:port`, which fails validation in some server libraries, as highlighted by https://github.com/libressl/portable/issues/660 . We should instead just set `cluster-service-name` as an SNI.
Remove port portion of the …
=> Remove port portion from destination to present FQDN as SNI

pkg/tunneldriver/driver.go
Some backends do odd tls things, like request renegotiation. By default, Go
rejects these. In the spirit of making this "just work", allow them to
renegotiate freely, since we're already accepting whatever cert they provide.
Eventually, we should make this configurable, but not today.
=> tunneldriver: add Renegotiation to forwarding tls config

docs/developer-guide/internal-crds.md, docs/user-guide/crds.md, docs/user-guide/tcp-edge.md, docs/user-guide/tcp-tls-edges.md
Add documentation for TLS and TCP edges.
Fills out the TCP edges guide, and includes TLS edge information there as well
since they're mostly the same.
None!
=> docs: document TLS and TCP edges

api/v1alpha1/ngrok_common.go, docs/deployment-guide/ngrok-regions.md, docs/developer-guide/internal-crds.md, docs/user-guide/crds.md, docs/user-guide/ingress-to-edge-relationship.md, docs/user-guide/ip-restrictions.md, docs/user-guide/route-modules.md, docs/user-guide/tcp-tls-edges.md, helm/ingress-controller/templates/crds/ingress.k8s.ngrok.com_httpsedges.yaml, helm/ingress-controller/templates/crds/ingress.k8s.ngrok.com_ngrokmodulesets.yaml, manifest-bundle.yaml
Updating the links in the k8s ingress controller for the new docs site
=> fix: update docs links for new docs site

helm/ingress-controller/Chart.yaml
Fix the artifacthub.io icon for [ngrok/kubernetes-ingress-controller](https://artifacthub.io/packages/helm/ngrok/kubernetes-ingress-controller). This updates the chart, so artifacthub should also pick up the verification file change (https://github.com/ngrok/kubernetes-ingress-controller/pull/332).
Updates icon to working link:
https://ngrok.github.io/kubernetes-ingress-controller/ngrok-favicon.svg
None
=> update icon to pull from helm http

helm/ingress-controller/templates/NOTES.txt
Closes: #325 
Lowercase the host in the ingress rule(s) provided by `NOTES.txt` after a helm install/upgrade.
Just pipe the random alpha num to the `lower` template function.
```
You can make this accessible via ngrok with the following manifest:
--------------------------------------------------------------------------------
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
name: test-app-1
namespace: default
spec:
ingressClassName: ngrok
rules:
- host: test-app-1-s3gmyzci.ngrok.app
http:
paths:
- path: /
pathType: Prefix
backend:
service:
name: test-app-1
port:
number: 80
--------------------------------------------------------------------------------
Applying this manifest will make the service "test-app-1"
available on the public internet at …
```
=> Lowercase domain name in helm NOTES.txt

helm/ingress-controller/Chart.lock, internal/controller/ingress/ingress_controller.go, internal/store/updatestorehandler.go
closes: #340
Ensures that the `Status.LoadBalancer.Ingress[].Hostname` field is set after the target CNAME is resolved on the `Domain`.
Add a call to `Driver.updateIngressStatuses` in the `UpdateStoreHandler.Update` method.
None
=> domain controller: run a driver sync after updating

helm/ingress-controller/templates/controller-deployment.yaml, helm/ingress-controller/tests/__snapshot__/controller-deployment_test.yaml.snap
related: #353
It came to light that these annotations should actually be on the pod rather than the deployment to force them to get recreated properly.
None, leaving the deployment annotations in place for now - just duplicating them to the pod template.
=> fix(helm): move other checksums to pod annotations

cmd/main.go, pkg/tunneldriver/driver.go
- Add `gateway-api` comment to client info
- Add `gateway-api` comment if `useExperimentalGatewayAPI` is set
=> add gateway to client info comment

cmd/main.go, helm/ingress-controller/README.md, helm/ingress-controller/templates/controller-deployment.yaml, helm/ingress-controller/values.yaml
Adds a helm value to set the API URL as an alternative to the `NGROK_API_URL` environment variable.
* Boring helm plumbing
* Keep the default from the environment, but override it if the helm value is set
None, since no one should have this helm value set. Existing users can continue with the env var and switch to the helm value at their leisure.
=> helm: add apiURL option

api/ingress/v1alpha1/ngrok_common.go, api/ingress/v1alpha1/ngrok_common_test.go, internal/controller/ingress/httpsedge_controller.go
FIxes an underlying bug when configuring oAuth providers that caused panics. Checking an interface for `nil` checks if it is nil, and not the underlying data.
Add `Provided() bool` to the `OauthProvider` interface that checks if it was provided and fix the nil check.
No
=> fix: panics in oauth providers

internal/store/cachestores.go, internal/store/driver.go
Resolves:
> 2024-05-16T17:41:30Z	ERROR	cache-store-driver	error updating object in create	{"UpdateStoreHandlerFor": "", "object": {"name": "simple-gatewayclass"}, "error": "unsupported object type: *v1.GatewayClass"}
Also logs when a gateway does not have an https listener (so cannot be used).
=> Add GatewayClass to cachestore

internal/store/driver.go, internal/store/driver_test.go
Adds ability for gateway api to use extensionRef to include a Policy CRD.
Adding a filter like this will plumb the policy data through:
```
- type: ExtensionRef
extensionRef:
group: ngrok.k8s.ngrok.com
kind: NgrokTrafficPolicy
name: my-traffic-policy
```
No
=> Add extensionRef support for policy crd inclusion

cmd/main.go, helm/ingress-controller/README.md, helm/ingress-controller/templates/controller-deployment.yaml, helm/ingress-controller/values.yaml, pkg/tunneldriver/driver.go
closes: #369 
Utilizes the `trusted` or `host` CA as the source of truth via a helm install flag.
Takes an install option for `--set rootCAs=host`  and plumb the `isHostCA` check into the `caCerts` for it to just get the host certs. 
- Build 2048 image, copying in cert and updating certs, apply changes
- Set `--set rootCAs host` and make deploy, no controller errors ✅ and can play example
- Set `--set rootCAs host` with canonical 2048 example without cert gives errors in controller
- Set `--set rootCAs trusted` no errors and plays 2048 as expected
- no set plays as expected
=> root-cas setting

internal/controller/ingress/tcpedge_controller.go, internal/controller/ingress/tlsedge_controller.go
Defensive coding in case the Tunnel Group Backend referenced by an edge does not actually exist. It is a pretty rare case, but if you hit it, you'll end up in a forever loop of not being able to create a new TCP/TLS Edge which isn't great.
If we get a 404 / `ngrok.IsNotFound(err) == true` when getting the backend referenced by the edge by ID, we can't hope to match on this edge and it is not a potential candidate for adoption, so just skip over it and continue the search.
No
=> Handle non-existent backend IDs more gracefully

internal/annotations/annotations.go, internal/annotations/compression/compression.go, internal/annotations/headers/headers.go, internal/annotations/ip_policies/ip_policy.go, internal/annotations/parser/parser.go, internal/annotations/tls/tls.go, internal/annotations/webhook_verification/webhook_verification.go
The annotations parser currently expects an ingress of type *networking.Ingress. We can make this more flexible for our use case and allow it to parse annotations from any `client.Object`. We'll want this shortly for being able to extract annotations from services for example in #375 
`*networking.Ingress` implements client.Object so all of our changes are just in the `internal/annotations` package.
No
=> refactor: annotations parsers to handle client.Object instead of just networking.Ingress

.github/workflows/ci.yaml, internal/controller/ingress/ippolicy_controller.go, internal/controller/ingress/ippolicy_controllers_test.go, internal/errors/errors.go, internal/errors/errors_test.go, internal/store/driver_test.go, internal/store/store.go, internal/store/store_test.go, pkg/tunneldriver/driver.go
We updated our `Makefile` with a `lint` target. This fixes the issues that are included in the default linters so that we can turn it on for CI to continually check that our code is being linted.
Fix linter warnings & add tests for places where it caught issues.
No
=> chore: Turn on golangci-lint

internal/store/driver.go
closes: https://github.com/ngrok/kubernetes-ingress-controller/issues/392
Bug fix: Correct tunnel group labels.
use httproute label rather than gateway label
Nope
=> assign tunnel group lable by httproute namespace

api/ingress/v1alpha1/ngrokmoduleset_types.go, api/ingress/v1alpha1/zz_generated.deepcopy.go, helm/ingress-controller/templates/crds/ingress.k8s.ngrok.com_ngrokmodulesets.yaml, internal/controller/ingress/service_controller.go, internal/store/driver.go
This allows users to specify termination behavior in a moduleset and then use it in the `k8s.ngrok.com/modules` annotation to terminate TLS at either the edge or the upstrem.
Since `EndpointTLSTermination` is a superset of `EndpointTLSTerminationAtEdge`, use the former in the moduleset so that it can be used when building both TLS & HTTPS Edges. When building the TLS configuration for HTTPSEdges created by the Ingress Controller, we have to convert `EndpointTLSTermination` to `EndpointTLSTerminationAtEdge` now.
No
=> feat: Support TLS termination in modulesets for Load Balancer Services

.github/ISSUE_TEMPLATE/controller_bug_report.yaml, helm/ingress-controller/Chart.lock
Fixes the controller bug report issue template. Currently it is not being shown due to an issue with the yaml
Move it onto a single line.
No
=> fix: Controller bug issue template

helm/ingress-controller/Chart.lock, internal/controller/ingress/service_controller.go
Fixes #405 
Fixes a bug where changing/adding annotations(ex: `k8s.ngrok.com/modules`) did not update the underlying TCP/TLS Edge spec. Also, the service controller was previously not watching for changes to ngrok modulesets or traffic policy CRs. This also fixes that.
* fix bug that was overwriting the desired state with the existing state
* Add watches & indexers so when a moduleset or traffic policy changes, we trigger a reconcile of services that use the moduleset or traffic policy
* Also pulls in an update to the bitnami/common library chart. We probably want to disable to auto update mechanism in favor of just building helm deps initially, but that is out of scope for this.
no
=> fix(service-controller): Updates not working

Makefile
These were causing more changes to get pulled in when a new chart was published. We are fine with having a slightly outdated library chart in exchange for it not changing out from under us
Just run `helm dependency build` instead of `helm dependency update`.
No
=> chore: Disable helm dependency auto-updates

go.mod, internal/store/driver.go, internal/store/driver_test.go, internal/util/k8s.go, internal/util/k8s_test.go
There are a some places where I think we can use generics and other methods to make the code easier to read, maintain, and test. The initial seed was one of those places that can benefit from this. I think we can also re-use the new `internal/util` package in more places too.
* Adds a generic function which can takes `[]T`, where `*T` implements `client.Object`, and returns `[]client.Object` 
* Adds a function that can fetch all items of a particular type and return them as `[]client.Object`
* refactors the driver Seed so we can easily see all the types we are seeding
This is slightly less memory efficient as rather than getting a pointer for each item before we call the store to update it, we pre-compute a slice with all pointers. This seemed like an acceptable trade-off for making the …
=> refactor: Easier to read driver seed

internal/store/store.go, internal/store/store_test.go
Was originally supposed to be completed in https://github.com/ngrok/kubernetes-ingress-controller/issues/56, but might have been a slight regression
Adds support for having multiple rules per ingress. Example:
```yaml
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
name: test-ingress
namespace: default
annotations:
k8s.ngrok.com/modules: "compression,tls,only-trusted-ips,circuit-breaker"
spec:
ingressClassName: ngrok
rules:
- host: my-test-app-4.ngrok.io
http:
paths:
- path: /
pathType: Prefix
backend:
service:
name: test-app-1
port:
name: http
- host: my-test-app-5.ngrok.io
http:
paths:
- path: /app-2
pathType: Prefix
backend:
service:
name: test-app-2
port:
name: http
- path: /app-1
pathType: Prefix
backend:
service:
name: test-app-1
port:
name: http
```
* We had a check that …
=> fix(store): Multiple ingress rules per ingress not working

internal/store/driver.go
Closes #148 
Allows for using wildcard domains via the ingress controller.
The algorithm for creating domains was to aggregate all of the `rules.Host`s from ingresses and the `listener.hostnames` from Gateways. This would give us a list of ngrok `Domain` CRs  to create/update. We currently replace `.` with `-` in the domain name to create the `Domain` CRs. This works fine expect that `*` are not valid in kubernetes resource names. So we now replace `*` with `wildcard` when generating the `Domain` CR Name.  This makes the name now a valid k8s name.
This could cause future problems if you want to reserve the domain `wildcard.example.com` as the name wouldn't be able to be distinguished from the one generated by `*.example.com` as they would both generate a `Domain` CR named …
=> feat: Support for wildcard domains

.github/workflows/install-relased-helm.yaml
While trying to reproduce #416, I made a GitHub Actions matrix job that allows us to install to do an e2e style deployment of our helm charts. We aren't providing an actual auth token or API key currently, so it will just fail to connect, but we can use this to validate that chart versions install properly along with the CRDs. If we do find a case that can re-create #416, this will also help serve as a regression test in the future.
Created a GitHub action that allows for `workflow_dispatch`, so we can test any of our helm chart versions. I chose the latest 4 versions of helm as well as k8s to test against using a kind cluster
No, this is an internal tool for testing.
=> feat(ci): Add a matrix style test for different versions of k8s & helm

.github/workflows/install-relased-helm.yaml, README.md, docs/developer-guide/releasing.md, docs/examples/hello-world/README.md, helm/ingress-controller/CHANGELOG.md, helm/ingress-controller/Chart.yaml, helm/ingress-controller/README.md, helm/ingress-controller/tests/__snapshot__/controller-deployment_test.yaml.snap, helm/ingress-controller/tests/__snapshot__/controller-pdb_test.yaml.snap, helm/ingress-controller/tests/__snapshot__/controller-serviceaccount_test.yaml.snap, helm/ingress-controller/tests/__snapshot__/ingress-class_test.yaml.snap
We are moving our repository to charts.ngrok.com
* Update references of our old helm chart repo to our new one.
* Update the icon location
No
=> chore(helm): Update docs and chart icon

README.md, helm/ingress-controller/CHANGELOG.md, helm/ingress-controller/Chart.yaml, helm/ingress-controller/templates/NOTES.txt, helm/ingress-controller/tests/__snapshot__/controller-deployment_test.yaml.snap, helm/ingress-controller/tests/__snapshot__/controller-pdb_test.yaml.snap, helm/ingress-controller/tests/__snapshot__/controller-serviceaccount_test.yaml.snap, helm/ingress-controller/tests/__snapshot__/ingress-class_test.yaml.snap
Add the project rename announcements
* Added announcement section at top of `README.md`
* Added announcement section at top of `NOTES.txt` (shown during `helm install`)
No
=> Add announcements for project rename

helm/ngrok-operator/templates/rbac/httpsedge_editor_role.yaml, helm/ngrok-operator/templates/rbac/httpsedge_viewer_role.yaml, helm/ngrok-operator/templates/rbac/ippolicy_editor_role.yaml, helm/ngrok-operator/templates/rbac/ippolicy_viewer_role.yaml, helm/ngrok-operator/templates/rbac/ngrokmoduleset_editor_role.yaml, helm/ngrok-operator/templates/rbac/ngrokmoduleset_viewer_role.yaml, helm/ngrok-operator/templates/rbac/tcpedge_editor_role.yaml, helm/ngrok-operator/templates/rbac/tcpedge_viewer_role.yaml, helm/ngrok-operator/templates/rbac/tlsedge_editor_role.yaml, helm/ngrok-operator/templates/rbac/tlsedge_viewer_role.yaml, scripts/helm-setup.sh
Similar to #436 
I noticed that a lot of our rbac policies were not templated out for helm and copied from the kubebuilder generation.
* Update them to match for consistency
* Bump helm unittest plugin to 0.6.1 (Not necessary, but updating dependencies is good)
=> Update RBAC helm templates

README.md
Current docs on the README are wrong since we haven't released this yet. Change back to the kubernetes-ingress-controller instructions until our first release.
* Updated to have kubernetes-ingress-controller docs
No
=> fix(docs): Change helm install to be from kubernetes-ingress-controller

cmd/main.go, helm/ngrok-operator/CHANGELOG.md, helm/ngrok-operator/README.md, helm/ngrok-operator/templates/controller-deployment.yaml, helm/ngrok-operator/templates/ingress-class.yaml, helm/ngrok-operator/tests/__snapshot__/controller-deployment_test.yaml.snap, helm/ngrok-operator/tests/controller-deployment_test.yaml, helm/ngrok-operator/tests/ingress-class_test.yaml, helm/ngrok-operator/values.yaml
Namespace the feature sets in Helm values
Collect each feature set and put it into a namespaced section:
```yaml
ingress:
enabled: true/false
...
gateway:
enabled: true/false
...
bindings:
enabled: true/false
...
```
I tried to make this backwards compatible but I suspect it's not 100% due to incompatible DeMorgan logic etc... between desired and expected behaviours.
So here's what's deprecated:
* Deprecate `useExperimentalGatewayApi`, instead use `gateway.enabled: true`
* Deprecate `ingressClass`, instead use `ingress.ingressClass`
* Deprecate `watchNamespace`, instead use `ingress.watchNamespace`
* Deprecate `controllerName`, instead use `ingress.controllerName`
=> Namespace Helm Values by Feature Set

helm/ngrok-operator/templates/binding-configuration.yaml, helm/ngrok-operator/tests/__snapshot__/binding-configuration_test.yaml.snap
when attempting to install the controller with binding enabled (like by using `make deploy_with_bindings`) it errors on main
```
Error: UPGRADE FAILED: cannot patch "default-configuration" with kind BindingConfiguration: BindingConfiguration.bindings.k8s.ngrok.com "default-configuration" is invalid: spec.allowedURLs: Required value
make: *** [deploy_with_bindings] Error 1
```
The casing is just incorrect so it doesn't get the default value of `"*"` and instead is null
=> Update template to use the correctly cased values property for allowed urls

pkg/bindingsdriver/driver.go, pkg/bindingsdriver/driver_test.go
Adds an initial bindings driver, similar to the TunnelDriver. This will be used in the bindings forwarder deployment to watch `EndpointBindings` and listen on a given port.
Adds a bindings driver, similar to the TunnelDriver. It will be wired up in a subsequent PR to actually listen in a deployment.
No
=> feat: Initial bindings driver

go.mod, go.sum, internal/ngrokapi/clientset.go
This will allow us to create the kubernetes operator api resource by using a pre-release of the ngrok-api-go client. Also will allow us to start using endpoints eventually as well.
Add ngrok-api-go(v6) from a branch. The API and client is subject to change, but we want to start building on this.
No, just adding in the new client & wiring it up.
=> feat: Add in v6 ngrok-api-go client

.github/workflows/generate-chart-readme.yaml, helm/ngrok-operator/README.md
Pulling this out of #465 since the github action runs on `pull_request_target` so that we can push back changes.
Updates the readme generator.
No
=> chore: Update readme-generator

Dockerfile, Makefile, cmd/api/main.go, cmd/bindings-forwarder/main.go, helm/ngrok-operator/README.md, helm/ngrok-operator/templates/_helpers.tpl, helm/ngrok-operator/templates/bindings-forwarder/deployment.yaml, helm/ngrok-operator/templates/bindings-forwarder/rbac.yaml, helm/ngrok-operator/templates/bindings-forwarder/service-account.yaml, helm/ngrok-operator/tests/agent/service-account_test.yaml, helm/ngrok-operator/tests/bindings-forwarder/__snapshot__/deployment_test.yaml.snap, helm/ngrok-operator/tests/bindings-forwarder/__snapshot__/rbac_test.yaml.snap, helm/ngrok-operator/tests/bindings-forwarder/__snapshot__/service-account_test.yaml.snap, helm/ngrok-operator/tests/bindings-forwarder/deployment_test.yaml, helm/ngrok-operator/tests/bindings-forwarder/rbac_test.yaml, helm/ngrok-operator/tests/bindings-forwarder/service-account_test.yaml, helm/ngrok-operator/tests/credentials-secret_test.yaml, helm/ngrok-operator/values.yaml, internal/controller/bindings/endpointbinding_controller.go, internal/controller/bindings/endpointbinding_controller_test.go, internal/controller/bindings/forwarder_controller.go, internal/controller/ngrok/kubernetesoperator_controller.go
This adds in a new bindings forwarder deployment. The bindings forwarder watches for `bindingsv1alpha1.EndpointBindings` CRs and listens on the desired port so that incoming connections destined for the service have something to connect to. We still need to wire this up to connect to ngrok and forward the bytes there so that the endpoint is fully bound. For now, we simply use an example connection handler that prints information about the connection and echos back what the user inputs.
* Added the initial bindings forwarder program, `bindings-forwarder-manager`. This sets up another manager and makes a new non leader elected controller with the `ForwarderReconciler`. The `ForwarderReconcile` listens starts and stop listening on the configured ports as needed.
* Added an example …
=> Bindings forwarder

go.mod, go.sum
Pulls in the latest changes from ngrok-api-go along with our k8s-operator branch that has the changes we need to dev for the k8s operator
* Rebase the ngrok-api-go `k8s-operator` branch on the ngrok-api-go `main` branch.
* `go get -u github.com/ngrok/ngrok-api-go/v6@k8s-operator`
* `go mod tidy`
No
=> chore: Update ngrok-api-go to pull in new changes

pkg/bindingsdriver/driver.go, pkg/bindingsdriver/driver_test.go
This wasn't working as I had originally intended. The problem is the for loop and only doing a select at the top of the for loop from the channel. `b.listener.Accept()` will block until there is a new conn to accept. This means that if we call `Stop()` on a bindings listener, it wouldn't actually try to `Close()` the listener until a new connection comes in, which isn't what we want. 
This fixes it so that we will only `Close()` the listener once and we will do it when `Stop()` is called for the first time. This will cause the `b.listener.Accept()` to return an error as well making sure that we immediately go back to the start of our for loop. Also, added some tests to make sure that the new code behaves as desired.
No
=> fix: Make sure that we can't connect after we stop the bindings listener

cmd/api/main.go, helm/ngrok-operator/templates/controller-deployment.yaml, helm/ngrok-operator/tests/__snapshot__/controller-deployment_test.yaml.snap, internal/controller/bindings/endpointbinding_poller.go
Ensure the endpoint poller does not start polling until a k8sop ID is retrieved
No.
=> Ensure endpoint poller does not start until k8sop is regestered with API

cmd/api/main.go, helm/ngrok-operator/templates/controller-deployment.yaml, helm/ngrok-operator/tests/controller-deployment_test.yaml, internal/controller/bindings/boundendpoint_controller.go, internal/controller/bindings/boundendpoint_poller.go, internal/controller/bindings/boundendpoint_poller_test.go, internal/util/helm.go, internal/util/helm_test.go
Implement propagating the target metadata (annotations and labels) to the target service created by BoundEndpoint
Add util.ParseHelmDictionary()
Use util.ParseHelmDictionary() for --ngrok-metadata
Add serviceAnnotations and serviceLabels flags to api binary
Propagate target metadata to target service
No.
=> Implement Target Metadata

cmd/api/main.go, go.mod, go.sum, internal/controller/bindings/boundendpoint_poller.go
This replaces the mock endpoints we had for testing with actually polling the API for bound endpoints.
* Pass the ngrokclientset into the poller
* Replace the mock endpoints we had with the results returned from the API
No
=> feat: BoundEndpointPoller polls from the API

internal/controller/base_controller.go, internal/controller/ingress/domain_controller.go
Fixes an issue where we would not retry to reconcile domains when receiving a 404 from the ngrok API. This could happen when the resource was deleted either in the dashboard or via the API outside of the ngrok operator.
* If a domain can't be found in the ngrok API, clear the status and return the original not found error
* Also, update our base controller's error handling to retry on not found errors. This was probably affecting all resources that were clearing their status but would not be re-reconciled because we were swallowing them in `CtrlResultForErr`.
No
=> fix: domain stuck when ID is not found

cmd/api/main.go, internal/controller/ngrok/kubernetesoperator_controller.go
Sometimes the TLS secret can be invalid:
```
% {kind-kind/ngrok-operator} kb get secret -oyaml ngrok-operator-default-tls
apiVersion: v1
data:
tls.crt: ""
tls.csr: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlHNk1HSUNBUUF3QURCWk1CTUdCeXFHU000OUFnRUdDQ3FHU000OUF3RUhBMElBQkFYbDlPcmE4TDNqV2orbwpjMDJvVE9KOHNXSU9ZUHRGa09vQVdFcWU5Qjk5N2NxU1dRK3dIY2VWQzY5MmQwMW0rYUNsUmozSXE4NjZ4Q0tGCnJlbWx3VGVnQURBS0JnZ3Foa2pPUFFRREJBTklBREJGQWlFQWpDOUJsb2JPU1I3VjdiSFlObTJiZ0FmT0lId2gKVlBDbDVaN3oyZkk2OS9BQ0lFRytlN1BURHByZUpRVHl4cVc1ZVUvU0srb3p4dmxvMWc1amhBSkQwTjRYCi0tLS0tRU5EIENFUlRJRklDQVRFIFJFUVVFU1QtLS0tLQo=
tls.key: LS0tLS1CRUdJTiBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0KTUhjQ0FRRUVJQjVjREFtQ0xIVDdNNzVYVURoTHhUb2I0dFBDdjhUVWNhdk9Cc1RJbkZDWW9Bb0dDQ3FHU000OQpBd0VIb1VRRFFnQUVC …
```
=> Ensure the TLS secret is valid otherwise upsert

internal/controller/bindings/boundendpoint_poller.go
Use a unique context so we can control the cancel rather than the ctrl manager.
=> Use unique context for endpoint poller reconcile actions

cmd/api/main.go, internal/store/driver.go
Attempts to provide a better migration path between the kubernetes-ingress-controller and the ngrok-operator. One of the problems identified is that it duplicates CRs in existing environments because the `k8s.ngrok.com/controller-name` and `k8s.ngrok.com/controller-namespace` labels (that we b/c owner references are not allowed cross namespace) do not match what the new operator thinks it should.
For the initial ngrok-operator release, include a migration on startup that will re-label the domains, httpsedges, and tunnels with the expected labels so that new objects are not created but are instead adopted.
No
=> fix: Better migration path from the ngrok kuberntes-ingress-controller to the ngrok-operator

api/bindings/v1alpha1/boundendpoint_types.go, api/ngrok/v1alpha1/kubernetesoperator_types.go, cmd/api/main.go, helm/ngrok-operator/templates/crds/bindings.k8s.ngrok.com_boundendpoints.yaml, helm/ngrok-operator/templates/crds/ngrok.k8s.ngrok.com_kubernetesoperators.yaml, helm/ngrok-operator/tests/controller-deployment_test.yaml, helm/ngrok-operator/values.yaml, internal/controller/bindings/boundendpoint_controller.go, internal/controller/bindings/boundendpoint_poller.go, internal/controller/bindings/boundendpoint_poller_test.go
Add regex validation to allowedURLs
Add conversion functions and tests
Create method to allow/deny BoundEndpoint projection
Deny BoundEndpoints based on allowedURLs
No.
=> Support allowedURLs

internal/controller/ingress/httpsedge_controller.go
Fixes the `HTTPSEdge` controller getting stuck when the httpsedge is not found in the ngrok API.
If the `HTTPSEdge` is not found, clear its status, update the status, and return the original not found error.
No
=> fix: Clear status and re-reconcile if httpsedge is not found

cmd/api/main.go
Hide `kind: KubernetesOperator` registration with ngrok API behind the bindings feature flag.
We're doing this so we can release v0.16.0 of ngrok-op without needing to figure out all the nitty-gritty details of k8sop registration (soon...)
No.
=> Hide ngrok-op API registration behind bindings feature flag

cmd/api/main.go, helm/ngrok-operator/README.md, helm/ngrok-operator/templates/agent/deployment.yaml, helm/ngrok-operator/templates/bindings-forwarder/deployment.yaml, helm/ngrok-operator/templates/controller-deployment.yaml, helm/ngrok-operator/tests/agent/deployment_test.yaml, helm/ngrok-operator/tests/controller-deployment_test.yaml, helm/ngrok-operator/values.schema.json, helm/ngrok-operator/values.yaml
We would like to support a 1-click installation for marketplace environments.
However, these environments do not allow users to provide required config before 1-click installing.
And, the installation is only successful if the Pod goes Ready (helm install success).
But, our ngrok-op requires user configuration to work, namely API key and authtoken.
So we provide this new `oneClickDemoMode: true/false` value that can change the behaviour of the installed ngrok-op.
- When true, ngrok-op will become Ready and log messages about missing required configuration.
- When false, ngrok-op will run in its normal operator mode (and report errors for missing fields as NotReady, etc...)
Factor out startup functions
Add oneClickDemoMode to …
=> Support one-click-demo mode

cmd/api/main.go, pkg/tunneldriver/driver.go
Ensure the ngrok-api-manager fails to start with error messages if the API key is invalid.
Dummy request to list API keys using the given API key
tunnel driver already errors for bad authtoken
```
2024-11-18T21:23:13Z	DEBUG	drivers.tunnel	decoded response	{"obj": "csess", "id": "7838d5221914", "sid": 3, "resp": {"Version":"","ClientId":"","Error":"The authtoken you specified is properly formed, but it is invalid.\nYour authtoken: 2lssG3MpQZ5dIyCVLYNRBfXC5tg_INVALID\nThis usually happens when:\n    - You reset your authtoken\n    - Your authtoken was for a team account that you were removed from\n    - You are using ngrok link and this credential was explicitly revoked\nGo to your ngrok dashboard and double check that your …
```
=> Error with invalid API key

.github/actions/build-and-test/action.yaml, .github/workflows/ci.yaml, .github/workflows/test.yaml, Makefile
- Ensure e2e cleanup steps always run
- Ensure build-and-test steps are always run on push to `main` branch
- Add debug information for the manager pod
=> Trigger ci e2e with Makefile change

internal/controller/bindings/boundendpoint_controller.go
For tcp endpoints (and http too but it's more noticeable with tcp endpoints because a healthcheck makes it all the way to your agent) the reconciliation loop for bound endpoints was triggering itself by updating the status at the end of an update, causing another update to trigger and so on. This PR adds a predicate so that empty status updates (and annotation updates) don't trigger another object reconciliation.
Adds predicates according to the controller-runtime docs: https://pkg.go.dev/sigs.k8s.io/controller-runtime@v0.17.4/pkg/predicate#AnnotationChangedPredicate
shouldn't be any!
Previously, you could see your bound endpoint endlessly reconciling really quickly, and the number of connections to your agent climbing quickly. Now, when starting a tcp endpoint you see much fewer …
=> skip no-op status and annotation updates for boundendpoint reconciliation

internal/controller/agent/agent_endpoint_controller.go, pkg/tunneldriver/driver.go, pkg/tunneldriver/utils.go, pkg/tunneldriver/utils_test.go
- Moves the agent endpoint url validation into its own utils file
- Fixes some issues with the initial logic
- Adds test coverage
=> fix endpoint url validation helper and add tests

internal/controller/agent/agent_endpoint_controller.go
I missed this copy/pasting the tunnel controller. We want to delete from the AgentEndpoint map, not the Tunnel map.
Delete from the AgentEndpointMap instead
No
=> fix(agent-endpoints): Delete agent endpoint instead of tunnel

scripts/release.sh
Updates the release script
Now that we are using a merge queue, we can't just look for merge commits since GitHub's merge queue will make a linear history with squash merging. Also we need to tell git log that our regexp is a PCRE regular expression.
No
=> feat(ci): Update release script

api/ngrok/v1alpha1/agentendpoint_types.go, helm/ngrok-operator/templates/crds/ngrok.k8s.ngrok.com_agentendpoints.yaml, internal/controller/agent/agent_endpoint_controller.go
Removed the required `type` field from agentendpoint trafficPolicy field and instead rely on "smarter" xvalidations to ensure that the field is properly configured. The enum still exists internally as a helper so that consumers don't need to check both fields.
=> remove boilerplate type field from trafficPolicy field

pkg/tunneldriver/driver.go
This fixes the agent endpoint getting created as a HTTPS endpoint even though the scheme in the url is HTTP.
* Add some extra logging
* If the URL scheme is `http`, add the scheme opt so that the endpoint is created as a http endpoint instead of https. We may want to consider fixing this in the ngrok SDK going forward.
No
=> Fix http endpoint scheme

api/common/v1alpha1/common_types.go, cmd/api/main.go, internal/controller/ingress/service_controller.go, pkg/managerdriver/driver.go
While working on migrating LB services from edges -> endpoints, I noticed that we weren't respecting the cluster domain configuration option. This makes it so that LB services also respect the configured cluster domain
* Set the default cluster domain const in the go code in 1 place, update the other places we reference it so we can change it in a single place.
No
=> fix(service-controller): Service controller uses configured cluster domain

helm/ngrok-operator/README.md, helm/ngrok-operator/templates/agent/deployment.yaml, helm/ngrok-operator/templates/bindings-forwarder/deployment.yaml, helm/ngrok-operator/templates/controller-deployment.yaml, helm/ngrok-operator/tests/agent/deployment_test.yaml, helm/ngrok-operator/tests/bindings-forwarder/deployment_test.yaml, helm/ngrok-operator/tests/controller-deployment_test.yaml, helm/ngrok-operator/values.schema.json, helm/ngrok-operator/values.yaml
Fixes #556 
Fixes `.Values.podLabels` being included in the deployments' `spec.selector.matchLabels`.
* Remove `podLabels` templates from the deployments' `spec.selector.matchLabels`.
* Add tests to verify that `podLabels` are added to the pod spec templates, but not the deployments' selector matchLabesl.
Yes, the `.Values.podLabels` were previously added incorrectly as additional selector labels. If you had previously supplied `.Values.podLabels`, you will need to delete the existing deployment. You can do this with minimal downtime by [deleting the deployment and orphaning the resources](https://kubernetes.io/docs/tasks/administer-cluster/use-cascading-deletion/#set-orphan-deletion-policy) controlled by the deployment.
=> fix(helm): .Values.podLabels should not be included in the deployment selectors

go.mod, go.sum
Update ngrok-api-go to a pre-release version to consume newer features https://github.com/ngrok/ngrok-api-go/commit/f9bc510716c0cdcb7c0991c44f80ccb31010fa9f
`go get -u github.com/ngrok/ngrok-api-go/v6@k8s-op-client`
*edit*: And run `go mod tidy` :man_facepalming: 
No
=> chore(deps): Update ngrok-api-go

.github/actions/build-and-test/action.yaml, Makefile, go.mod, go.sum
Our code gen was wrong for getting bound endpoints on a kubernetes operator. This updates to a version that shouldn't panic.
* Fix and regen our client
* Update to using the fixed version :crossed_fingers: 
No
=> fix(ngrok-api-go): Update to client that doesn't panic for get_bound_endpoints

internal/errors/errors.go, internal/secrets/resolver.go, internal/trafficpolicy/policy.go, internal/trafficpolicy/policy_test.go, internal/trafficpolicy/testdata/policy-1.json, internal/trafficpolicy/testdata/policy-2.json, internal/util/traffic_policy.go, internal/util/traffic_policy_test.go
Adds a new `trafficpolicy` package for creating traffic policy. It also adds new `util` function to convert a moduleset to a traffic policy.
Add utilities for creating adding rules and actions to a traffic policy. Create helpers to create actions for each type of action. Write the translation logic that converts modulesets to traffic policy with tests for each.
No. All net new utilities
=> feat: Add trafficpolicy package and conversion util

pkg/managerdriver/suite_test.go
Add back test to run Ginko specs for the manager driver. We had the test copied over in https://github.com/ngrok/ngrok-operator/pull/553, but Ginko needs a go test to run the specs.
Add the test back so that Ginko runs and we test more code.
No
=> fix: managerdriver tests not being run

.github/actions/changes/action.yaml, .github/workflows/ci.yaml
Help us get a better idea of what code we could do a better job of covering with tests
Use Codecov to upload coverage reports
No
=> feat(ci): Use codecov for coverage reports

pkg/tunneldriver/driver.go
We can't delete agent endpoints when the `AgentEndpoint` custom resources are deleted because we never add them to the map that tracks them. Adding the entry to the map makes this work as intended.
=> add newly created agent endpoints to the map

codecov.yml, internal/controller/ingress/httpsedge_controller.go
When migrating back to edges from endpoints, the httpsedges controller does not retry on the 'hostport already in use'. It should retry because the cloudendpoint may not have been deleted yet and the hostport is still in use.
* Re-reconcile on hostport conflict
* Add codecov.yml to control how codecov treats status checks
No
=> fix(httpsedges): HTTPS Edges should retry on hostport already in use

codecov.yml
Minor change to our codecov.yml file so it stops showing red X on merges for now. We're in the process of mocking out the ngrok API and SDKs so that we can increase testing coverage, but we aren't there yet.
Patch status is informational only.
No
=> chore(ci): Make codecov patch status informational for now as well

internal/controller/ingress/domain_controller.go, internal/controller/ingress/httpsedge_controller.go, internal/controller/ingress/ippolicy_controller.go, internal/ngrokapi/bindingendpoint_aggregator_test.go, internal/ngrokapi/clientset.go, internal/ngrokapi/edge_modules_clientset.go, internal/ngrokapi/edge_modules_https_clientset.go, internal/ngrokapi/edge_modules_tcp_clientset.go, internal/ngrokapi/edge_modules_tls_clientset.go
Step 1 in beefing up our test coverage. Rather than returning clients for everything, return interfaces that behave like the actual clients. This will allow us to rely on the interfaces in the rest of the code and eventually substitute mock clients so we can test the behavior of our controllers better.
Make interfaces for our clients and replace the actual implementation with the interfaces.
No
=> refactor(ngrokapi): Refactor ngrokapi package to better support mocking

api/bindings/v1alpha1/boundendpoint_types.go, helm/ngrok-operator/templates/crds/bindings.k8s.ngrok.com_boundendpoints.yaml, internal/controller/base_controller.go, internal/controller/bindings/boundendpoint_controller.go, internal/controller/bindings/boundendpoint_controller_test.go, internal/controller/bindings/boundendpoint_poller_test.go, internal/controller/ngrok/kubernetesoperator_controller.go, internal/ngrokapi/enriched_errors.go
Add support for `ngrok.Error` and enriched errors
New package
=> Add ngrok enriched errors

api/ngrok/v1alpha1/cloudendpoint_types.go, go.mod, helm/ngrok-operator/templates/crds/ngrok.k8s.ngrok.com_cloudendpoints.yaml, internal/annotations/annotations.go, internal/annotations/annotations_test.go, internal/controller/ingress/service_controller.go, internal/controller/ngrok/cloudendpoint_controller.go, internal/ir/ir.go, pkg/managerdriver/testdata/translator/endpoint-ingress-default-backend-conflict.yaml, pkg/managerdriver/testdata/translator/endpoint-ingress-namespace-conflict.yaml, pkg/managerdriver/testdata/translator/endpoint-ingress-pooling-conflict.yaml, pkg/managerdriver/testdata/translator/endpoint-ingress-trafficpolicy-conflict.yaml, pkg/managerdriver/translate_ingresses.go, pkg/managerdriver/translator.go, pkg/managerdriver/translator_test.go
- adds support in the `CloudEndpoint` CRD for endpoint pooling configuration (default false)
- passes this configuration to the API calls to create/update endpoints
- updates the `Ingress` -> `CloudEndpoint` translation to set the new field when the annotation `"k8s.ngrok.com/pooling-enabled": "true"` is present on the ingress.
- ingresses with pooling enabled must have matching traffic policy annotations and must all have pooling enabled in order to share a url.
- updates the `Service` -> `CloudEndpoint` translation to set the new field as well
=> add cloud endpoint pooling support

api/ngrok/v1alpha1/kubernetesoperator_types.go, helm/ngrok-operator/templates/crds/ngrok.k8s.ngrok.com_kubernetesoperators.yaml
The printed columns for the kubernetes operator resource was referencing the deleted Name field and didn't include endpoint selectors, so this changes that!
Modify kubebuilder annotations to update the printed columns for the kubernetes operator resource.
Does change the "additionalPrinterColumns" field on the kubernetes operator spec but I don't _think_ that should break anything?
=> for the k8s operator resource, remove binding name printcolumn and add endpoint selectors

internal/trafficpolicy/policy.go, internal/trafficpolicy/policy_test.go, internal/trafficpolicy/testdata/policy-2.json, internal/util/traffic_policy.go, internal/util/traffic_policy_test.go
We now have traffic policy actions for OAuth and OIDC. This PR adds typed actions for these and updates the ModuleSet -> TrafficPolicy utility conversion function.
* Add more actions to the trafficpolicy package.
* Updates the conversion function to convert OAuth and OIDC Modulesets -> TrafficPolicy
* Adds more tests
No
=> Oauth & OIDC conversion

api/ngrok/v1alpha1/agentendpoint_types.go, api/ngrok/v1alpha1/cloudendpoint_types.go, helm/ngrok-operator/templates/crds/ngrok.k8s.ngrok.com_agentendpoints.yaml, helm/ngrok-operator/templates/crds/ngrok.k8s.ngrok.com_cloudendpoints.yaml, internal/annotations/annotations.go, internal/annotations/annotations_test.go, internal/controller/ingress/service_controller.go, internal/ir/ir.go, pkg/managerdriver/testdata/translator/endpoint-ingress-default-backend-conflict.yaml, pkg/managerdriver/testdata/translator/endpoint-ingress-namespace-conflict.yaml, pkg/managerdriver/testdata/translator/endpoint-ingress-pooling-conflict.yaml, pkg/managerdriver/testdata/translator/endpoint-ingress-trafficpolicy-conflict.yaml, pkg/managerdriver/translator.go, pkg/managerdriver/translator_test.go
Add an additional annotation to support bindings on ingress
Update Cloud and Agent Endpoints Bindings to Kubernetes from k8s/*
Update Internal Agent Endpoints to be created with internal bindings
Update Cloud Endpoints to be created with whatever binding is being sent with annotation
=> add bindings annotation

internal/controller/ngrok/kubernetesoperator_controller.go, internal/controller/ngrok/kubernetsoperator_controller_test.go
The operator feature names had to be uppercase to conform to the api but now lowercase feature names are supported (and preferred).
lowercase the feature name strings
none
=> feature names can be lowercase

cmd/agent/main.go, cmd/api/main.go, helm/ngrok-operator/README.md, helm/ngrok-operator/templates/_helpers.tpl, helm/ngrok-operator/templates/rbac/role.yaml, helm/ngrok-operator/tests/__snapshot__/controller-deployment_test.yaml.snap, helm/ngrok-operator/tests/agent/__snapshot__/deployment_test.yaml.snap, helm/ngrok-operator/tests/controller-deployment_test.yaml, helm/ngrok-operator/values.schema.json, helm/ngrok-operator/values.yaml, internal/controller/gateway/namespace_controller.go, internal/controller/gateway/referencegrant_controller.go, internal/store/cachestores.go, internal/store/store.go, pkg/managerdriver/driver.go, pkg/managerdriver/endpoints.go, pkg/managerdriver/testdata/translator-disable-refgrants/gwapi-gateway-tls-cross-namespace.yaml, pkg/managerdriver/testdata/translator-disable-refgrants/gwapi-service-cross-namespace.yaml, pkg/managerdriver/testdata/translator/gwapi-gateway-allowed-routes-all-namespaces.yaml, pkg/managerdriver/testdata/translator/gwapi-gateway-allowed-routes-selector.yaml, pkg/managerdriver/testdata/translator/gwapi-gateway-tls-no-valid-referencegrants.yaml, pkg/managerdriver/testdata/translator/gwapi-gateway-tls-valid-referencegrants.yaml, pkg/managerdriver/testdata/translator/gwapi-no-valid-referencegrants.yaml, pkg/managerdriver/testdata/translator/gwapi-valid-referencegrants.yaml, pkg/managerdriver/translate_gatewayapi.go, pkg/managerdriver/translator.go, pkg/managerdriver/translator_test.go
**Note: This PR branches off of https://github.com/ngrok/ngrok-operator/pull/588 since it builds upon the GatewayAPI -> Endpoints work. This PR is not worth reviewing until that merges**
Makes ReferenceGrants required by default for:
- Referencing a Service in another namespace from an HTTPRoute
- Referencing a Secret in another namespace from a Gateway
- Referencing a Secret in another namespace from a Gateway
Per Gateway API, references in the same namespace do not require ReferenceGrants.
Added the ability to opt-out of ReferenceGrant support with the `gateway.disableReferenceGrants` helm value (default=false) which configures the `--disable-reference-grants` flag in the deployment.
Somewhat related: also fixes the faulty logic in the `allowedRoutes.Namespaces.Selector` field of …
=> feat: gwapi ReferenceGrant support

cmd/agent/main.go, cmd/api/main.go, helm/ngrok-operator/README.md, helm/ngrok-operator/tests/__snapshot__/controller-deployment_test.yaml.snap, helm/ngrok-operator/tests/agent/__snapshot__/deployment_test.yaml.snap, helm/ngrok-operator/values.schema.json, helm/ngrok-operator/values.yaml
This PR aims to auto enable support for Gateway API when possible:
- Gateway API support flag changed from disabled by default to enabled by default
- When flag is omitted, default is enabled instead of disabled
- When enabled, we check if the Gateway API CRDs are installed first
- If they are, we enable the Gateway API feature set
- If they are not, we log that the Gateway API CRDs were not detected and the feature set will be disabled
I didn't want to remove the flag itself and rely solely on the CRD check for two reasons:
- Users may have the Gateway API CRDs installed in the cluster but not want to use them with the ngrok operator, so they should be able to disable that feature set and not waste resources running controllers for something they don't intend to use
- Users upgrading …
=> auto enable gateway api support

internal/annotations/annotations.go, internal/annotations/annotations_test.go, internal/controller/ingress/service_controller.go, internal/store/store.go, internal/store/store_test.go, pkg/managerdriver/domains.go, pkg/managerdriver/driver_test.go, pkg/managerdriver/edges.go, pkg/managerdriver/testdata/translator/gwapi-gateway-default-to-endpoints.yaml, pkg/managerdriver/testdata/translator/gwapi-gateway-no-endpoints.yaml, pkg/managerdriver/testdata/translator/ingress-no-endpoints.yaml, pkg/managerdriver/testdata/translator/ingress-valid-default-to-endpoints.yaml, pkg/managerdriver/translate_gatewayapi.go, pkg/managerdriver/translate_ingresses.go
For the last few builds, we've required the `k8s.ngrok.com/mapping-strategy: endpoints` annotation on `Ingress` and `Gateway` resources in order for them to generate `AgentEndpoint` and `CloudEndpoint` resources instead of Edges. This makes endpoints the new default when the annotation is not supplied. Supplying `k8s.ngrok.com/mapping-strategy: edges` will still allow you to create Edges instead of Endpoints, but Edges are being removed soon.
=> default to using endpoints instead of edges for ingress/gateway API

.github/workflows/ci.yaml, Dockerfile, Makefile, flake.lock, flake.nix, scripts/preflight.sh
Upgrade to go 1.24.1. Looks like there might be some free perf improvements.
* Change references from 1.23 -> 1.24
* Also update golangci-lint to a version that supports 1.24
No
=> chore(deps): Upgrade go to 1.24.1

api/ngrok/v1alpha1/kubernetesoperator_types.go, helm/ngrok-operator/templates/crds/ngrok.k8s.ngrok.com_kubernetesoperators.yaml, internal/controller/ngrok/kubernetesoperator_controller.go
Adds a new field to `KuebrnetesOperatorStatus` that will be filled in with the `.Bindings.IngressEndpoint` url returned by the ngrok API response to a create/update.
We'll consume that status field in the next PR to use that url when forwarding traffic to ngrok instead of using the field that's set from `values.yaml` (and remove that option from `values.yaml`).
Check the ngrok API response and set the new field appropriately any time `updateStatus` is called on the KubernetesOperator resource.
Does add a new field on our KubernetesOperator resource so that resource will have to be updated when updating the operator.
=> Add IngressEndpoint to KubernetesOperatorStatus

internal/ir/ir.go, pkg/managerdriver/driver_test.go, pkg/managerdriver/testdata/translator/ingress-app-protocols.yaml, pkg/managerdriver/translate_ingresses.go, pkg/managerdriver/translator.go, pkg/managerdriver/translator_test.go, pkg/managerdriver/tunnels.go, pkg/managerdriver/utils.go
Fixes #572 
This is a fix for 2 issues:
* If the `appProtocol` on a service was unknown, we were throwing an error instead of ignoring it. According to the [docs](https://kubernetes.io/docs/concepts/services-networking/service/#application-protocol), valid values are any of the [IANA standard service names](https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xhtml). If we don't have a specific protocol mapped, we should probably ignore it.
* We weren't setting the upstream protocol on AgentEndpoints when converting from ingresses. This was breaking support for HTTP/2 upstreams when using endpoints.
* For the first part, try to map the `appProtocol` to one of our known protocols. If the `Tunnel.protocol` isn't able to be determined, just leave it empty …
=> fix: HTTP/2 upstreams for edges & endpoints

internal/controller/ngrok/kubernetesoperator_controller.go, tests/chainsaw/operator-registration/chainsaw-test.yaml
Fixes an empty TLS cert on operator creation. The `:=` assignment was shadowing and creating a new `tlsSecret` variable scoped to the if statement.
* Unshadow it to fix
* Modify the test to make sure that its not empty.
No
=> fix: Empty TLS cert on creation when bindings are enabled

api/ingress/v1alpha1/ngrokmoduleset_types.go, api/ingress/v1alpha1/ngrokmoduleset_types_test.go, flake.nix, internal/controller/util.go, pkg/managerdriver/driver.go, pkg/managerdriver/driver_test.go, pkg/managerdriver/translate_ingresses.go
When using the `edges` mapping-strategy, the `traffic-policy` annotation on ingresses was not getting correctly copied over to the edge routes.
* Added a test to exercise the bug
* Slight refactor to fix the bug
No
=> fix: traffic-policy annotation not working when using mapping-strategy of edges

internal/controller/bindings/forwarder_controller.go, internal/controller/bindings/forwarder_controller_test.go
We're moving ingress endpoints to be something that's always provided by the ngrok api instead of something configurable by the user. This change starts using the ingress endpoint that's set on the KubernetesOperator status instead of the one on the spec.
We'll (eventually) remove it from the spec and chart.
Get the ingress url off the status instead of spec.
If you have a very old operator that hasn't ever gotten the ingress endpoint from the API it may stop working, but any update from the controller should fill it in.
=> Consume IngressEndpoint from status

cmd/api/main.go
Currently the KubernetesOperator resource always sets its `Description` field based on the default value for the crd. Since we're asking users for description in values.yaml, we should set it based on that instead.
Set description from Values.description.
Nope!
=> set operator description from values.yaml description

cmd/api/main.go, internal/annotations/annotations.go, internal/controller/agent/agent_endpoint_controller.go, internal/controller/ingress/service_controller.go, internal/controller/ngrok/cloudendpoint_controller.go, internal/controller/ngrok/cloudendpoint_controller_test.go
This should fix #618
When using the endpoints mapping strategy, LB services weren't working and were stuck in progressing due to the cloud endpoints not being able to be created. The long term plan is that CloudEndpoints and Agent Endpoints can handle a URL like `tcp://` by reserving one. Ideally, this is even handled in the ngrok API for you.
For now, we need a workaround for this.
* There is a new annotation `k8s.ngrok.com/url` that more closely matches the semantics of the ngrok CLI command.
* If the `k8s.ngrok.com/url` annotation is unspecified, we fall back to the old `k8s.ngrok.com/domain` annotation and warn that this annotation is deprecated.
* This isn't a great long term solution, but since making CLEP and AEP understand how to reserve addrs is a bigger refactor, we reserve a …
=> Lb services reserve tcp addr for endpoints

.github/workflows/trivy-image-scan.yaml
Enables a job that will run on merge to main and every Monday at ~8:00 Pacific (at least one of us who works on the operator should be awake and online by then). The job builds an image from main and uses trivy to scan the built image for vulnerabilities.
=> enable trivy container scanning job

cmd/api/main.go, pkg/managerdriver/driver.go, pkg/managerdriver/translator_test.go
Ran into a panic locally on the latest release when having the Gateway API CRDs installed, but without the TCP & TLS Route CRDs. This should fix the panic.
1. Only try to read the resource list from the dynamic client for `gateway.networking.k8s.io/v1alpha2` if the `err == nil`. This  fixes the panic.
2. We also need to conditionally seed `&gatewayv1alpha2.TCPRoute{})` and `&gatewayv1alpha2.TLSRoute{})` only if they are enabled.
No
=> fix(api-manager): panic when TCP/TLS Route CRDs are not installed.

api/ingress/v1alpha1/domain_types.go, helm/ngrok-operator/templates/crds/ingress.k8s.ngrok.com_domains.yaml, internal/controller/ingress/domain_controller.go
Domains are somewhat unique among the ngrok API types, especially ngrok managed domains. Once you reserve one, it belongs to you. If you delete it, it is released back into the pool and someone else can reserve it. Since domains also count against your limits, sometimes you want to delete them if they are only used temporarily so it doesn't impact your account limits. Other times, you want to keep the domain around as it is a well known domain that you want to use again.
This adds a reclaim policy to domains. If the `reclaimPolicy == "Delete"`, the domain is deleted from your account when the `Domain` CR is deleted. If the `reclaimPolicy == "Retain"`, the domain is not deleted from your account and only the CR is deleted.
In a subsequent PR, we'll be plumbing this value through the helm …
=> feat: Add a reclaimPolicy to domains

api/ngrok/v1alpha1/cloudendpoint_types.go, helm/ngrok-operator/templates/crds/ngrok.k8s.ngrok.com_cloudendpoints.yaml
Adds the `.status.id` field from the CloudEndpoint to the list of printer columns, so you can more easily see which cloud endpoint it is.
* Add kubebuilder marker for "ID" printcolumn.
No
=> feat(cloud-endpoints): Add CloudEndpoint ID to printer column

internal/controller/gateway/gateway_controller.go, internal/controller/gateway/gateway_controller_test.go, internal/controller/gateway/gatewayclass_controller.go, internal/controller/gateway/gatewayclass_controller_test.go, internal/controller/gateway/httproute_controller.go, internal/controller/gateway/httproute_controller_test.go, internal/controller/gateway/suite_test.go, internal/testutils/k8s-resources.go, tools/make/_common.mk, tools/make/test.mk
The Gateway API specificies that conditions should be set on resources when they are accepted, programmed, and ready.
This tackles the first part by setting accepted conditions on resources along with the status and reason for the condition.
* refactored the gatewayclass controller tests to use some more shrared helpers
* Added tests for gateway and http route resources to verify that they have the appropriate accepted condition
* Updated the gateway and http route reconcilers to set the accepted condition
*No
=> feat(gateway-api): Set accepted conditions on gateways & httproutes

internal/controller/gateway/gateway_controller_test.go, internal/controller/gateway/suite_test.go, pkg/managerdriver/driver.go, tools/make/test.mk
This updates the gateway status addresses so that our Gateway API implementation can be used in conjunction with tools like external DNS.
* In the manager driver, we loop through each of the gateways and calculate their addresses from the list of domains.
* Start a Domain Reconciler with a mocked domain client in the gateway suite tests to provide statuses for domain objects so we can test what happens when there is and isn't a CNAME target for a gateway Domain.
* TODO: There is still a good amount of work to be done on updating all of the Listener Status conditions to conform with the spec and some edge cases that need to be handled for what happens when a gateway is invalid.
No
=> feat(gateway-api): Add gateay status addresses

cmd/agent-manager.go, cmd/api-manager.go, cmd/common.go, helm/ngrok-operator/README.md, helm/ngrok-operator/templates/agent/deployment.yaml, helm/ngrok-operator/templates/controller-deployment.yaml, helm/ngrok-operator/tests/__snapshot__/controller-deployment_test.yaml.snap, helm/ngrok-operator/tests/agent/__snapshot__/deployment_test.yaml.snap, helm/ngrok-operator/tests/agent/deployment_test.yaml, helm/ngrok-operator/tests/controller-deployment_test.yaml, helm/ngrok-operator/values.schema.json, helm/ngrok-operator/values.yaml, internal/controller/agent/agent_endpoint_controller.go, internal/controller/gateway/httproute_controller_test.go, internal/controller/ngrok/cloudendpoint_controller.go, internal/store/store_test.go, internal/testutils/k8s-resources.go, pkg/managerdriver/domains.go, pkg/managerdriver/driver.go, pkg/managerdriver/driver_test.go
See https://github.com/ngrok/ngrok-operator/pull/641 for more context
Now that Domains have a Reclaim Policy, we can set a default Domain Reclaim Policy for Domains created by the operator. It respects existing created domain CRs deletion policy. For example, if a domain CR was created manually with a Reclaim Policy of Retain, and the `defaultDomainReclaimPolicy` is set to Delete, it will not overwrite the existing ReclaimPolicy of Retain.
* Add a setting for `defaultDomainReclaimPolicy` to the helm chart
* Pass the defaultDomainReclaimPolicy through to the driver and the Controllers that need it
* Only set the Reclaim Policy on creates
No. The current domain Reclaim Policy defaults to "Delete" and the `defaultDomainReclaimPolicy` mirrors this. We still do not delete Domain CRs when they …
=> feat: Add a default domain reclaim policy

pkg/tunneldriver/driver.go
When an upstream deployment behind a service was scaled down to 0, dialing the service would give a connection refused. We weren't closing the ngrok connection when this happened, causing the connection to hang.
* If we are unable to dial the upstream, close the ngrok connection so that a user gets a better error message as opposed to just having the client connection hang.
* Also, add a default dial timeout since the context we pass in is much longer lived and will result in us trying to dial for a long time.
No
=> fix: Hanging connections

.golangci.yml, internal/annotations/annotations_test.go, internal/annotations/parser/parser.go, internal/controller/agent/agent_endpoint_controller.go, internal/controller/agent/tunnel_controller.go, internal/controller/bindings/boundendpoint_controller.go, internal/controller/bindings/forwarder_controller.go, internal/controller/ingress/domain_controller.go, internal/controller/ingress/httpsedge_controller.go, internal/controller/ingress/ippolicy_controller.go, internal/controller/ingress/service_controller.go, internal/controller/ingress/tlsedge_controller.go, internal/mocks/nmockapi/iter_test.go, internal/ngrokapi/bindingendpoint_aggregator.go, internal/util/traffic_policy_test.go, pkg/managerdriver/driver.go, pkg/managerdriver/driver_test.go, pkg/managerdriver/edges.go, pkg/managerdriver/translate_gatewayapi.go, pkg/managerdriver/translate_ingresses.go, pkg/managerdriver/translator.go, pkg/managerdriver/tunnels.go, pkg/managerdriver/utils.go, pkg/tunneldriver/driver.go
Came up during review of #658. Figured we should fix it across the codebase and enable a linter versus just fixing it there.
We aren't very consistent about using `errors.New` over `fmt.Errorf` and had a lot of places where we were using the latter. This enables the revive linter for this to prefer using `errors.New` in places it can be used.
* Enable the revive linter `use-errors-new`
* Fix all the linter warnings for `fmt.Errorf`
No
=> perf: Enable 'use-errors-new' revive linter

.github/workflows/generate-full-install-manifests.yaml, .github/workflows/install-relased-helm.yaml, manifest-bundle.yaml, tools/make/generate.mk
I noticed we aren't updating the manifest bundle and its fairly out of date. This adds a make command to easily keep this updated. We aren't doing any automation on this currently when we do a release and should think about doing that going forward. For now though, this updates it and gives us a consistent way to do that.
* Add a make command for generating the manifest bundle
* Update the GH workflow that referenced it
No
=> fix: Update manifest-bundle.yaml

helm/ngrok-operator/Chart.lock, helm/ngrok-operator/Chart.yaml
Migrate off `https://charts.bitnami.com/bitnami` and to their OCI repository.
Migrate from bitnami's current helm chart repository to their OCI repository. Also, update the version of the library chart.
No
=> chore(helm): Migrate to bitnami OCI library chart
