- go.mod
- go.sum
- internal/controllers/main.go
- pkg/ngrokapidriver/driver.go
Fixes #49 
Currently setting it `ngrok-ingress-controller/v1-alpha` but open to any other suggestions or if we want to tackle compiling it with a version at this time.
> Add custom user agent

- .github/workflows/generate-chart-readme.yaml
- helm/ingress-controller/README.md
- helm/ingress-controller/values.yaml
Contributes to #36 
Update `values.yaml` with comments that make it easier to generate README documentation.
> Document values.yaml and automatically generate it for the README.md

- .github/workflows/ci.yaml
- Makefile
- helm/ingress-controller/.helmignore
- helm/ingress-controller/README.md
- helm/ingress-controller/tests/__snapshot__/controller-rbac_test.yaml.snap
- helm/ingress-controller/tests/controller-cm_test.yaml
- helm/ingress-controller/tests/controller-rbac_test.yaml
- helm/ingress-controller/values.yaml
- scripts/helm-setup.sh
Resolves #36 
Adds helm `unittest` plugin to project with snapshots so we can validate helm generates what we want it to
> Setup testing for helm

- docs/releases.md
Contributes to: #60 
Documentation on our release process
Describes what artifacts we will build and release, where they are published to, how we will version them, and their how it maps to git tags. We can then automate our release process to conform with our documentation.
No
> Add initial Release Process documentation

- helm/ingress-controller/CHANGELOG.md
- helm/ingress-controller/Chart.yaml
- helm/ingress-controller/templates/NOTES.txt
- helm/ingress-controller/tests/__snapshot__/controller-deployment_test.yaml.snap
- helm/ingress-controller/tests/__snapshot__/controller-serviceaccount_test.yaml.snap
- helm/ingress-controller/tests/__snapshot__/ingress-class_test.yaml.snap
Fixes #89 
Fixes 'break' is not a function
Removes calling "break"
No
> :bug: Fix rending of NOTES.txt

- go.mod
- internal/annotations/annotations.go
- internal/annotations/annotations_test.go
- internal/annotations/compression/compression.go
- internal/annotations/parser/parser.go
- internal/controllers/domain_controller.go
- internal/errors/annotations.go
- internal/errors/errors.go
* Adds an internal `errors` package so we can typecheck errors
* Adds annotation parsing so we can use these to help build out the route modules
* Refactor the domain controller
No
> Errors and annotations

- .github/labeler.yml
- .github/workflows/labeler.yml
Fixes #115
Automatically add labels based on files changed
Use the `actions/labeler` github action to automatically label PRs.
No
> Automatically label PRs

- Makefile
- examples/ingress-class/ingress-class.yaml
- scripts/e2e.sh
Small updates to the makefile and e2e files for testing ingress classes
- automatically restart pods after `make deploy`
- give the ingress class example its own service backend
- update e2e script to stop trying to remove domains and to not try to fully delete the namespace. Deleting the domains and then immediately trying to re-register them can cause them to not be available. And if we don't delete the domains, the namespace delete hangs. This isntead relies on the controller to do the appropriate amount of cleanup
no
> Small updates to the makefile and e2e files for testing ingress classes

- .github/workflows/ci.yaml
- go.mod
Tidy up the go.mod file and add a PR check to make sure it has been run
Run go mod tidy in CI and if the go.mod or go.sum file have changed, fail the check
No
> Tidy up go.mod

- docs/user-guide/route-modules.md
Adds documentation for `NgrokModuleSet`s along with examples of how to use them. I think we'll want to add more examples to this over time, especially for OAuth.
No
> Add route module documentation

- README.md
This diagram is out of date, lets just point people to the developer-guide
> Remove icepanel link from README.md

- helm/ingress-controller/README.md
- helm/ingress-controller/templates/controller-deployment.yaml
- helm/ingress-controller/values.yaml
- scripts/helm-setup.sh
This is an analog to `podAnnotations`.
This seems both relatively common, and like a useful thing to have.
I also made some minor wording tweaks, and I'm happy to teak any that seem off the mark.
> Add a 'podLabels' option to the helm chart

- .envrc
- .gitignore
- docs/developer-guide/README.md
- flake.lock
- flake.nix
Add a .envrc and flake.nix to provision development tooling via nix and
direnv.
> misc: add direnv and a nix devshell

- internal/controllers/domain_controller.go
- internal/controllers/httpsedge_controller.go
- internal/controllers/ingress_controller_test.go
- internal/controllers/ippolicy_controller.go
- internal/controllers/tcpedge_controller.go
- internal/controllers/tunnel_controller.go
- pkg/tunneldriver/driver.go
Just quieting my IDE, nothing (much) to see here.
> resolve some linter warnings

- flake.nix
> nix: use the *actual* helm, not the synthesizer

- README.md
Changelog:
- Updated introduction to be streamlined introduction of the project and capabilities. 
- Future task: create an exhaustive list of feature-sets below overview.
- Added table of contents to the top of the readme with important links
- Added a note about helm being recommended way for installation over manifest
- Merged Helm and YAML manifests installation into single section
- Changed notes to use new Github note callout feature
- Changed repository images to take up less space and left aligned content
- Changed it so all badges are on the same line
- Changed code blocks from `bash` to `sh` to enable code highlighting
- Moved account requirement to top of the readme for better visibility
- Moved warning to known issue section
> chore(readme): improve structure and content

- .envrc
I noticed `$GOPATH` wasn't setting correctly in my shell (fishshell), so this fixes it.
Change `.envrc` to use `layout go` which updates `$GOPATH` and `$PATH` automatically.
None
> use direnv layout feature

- helm/ingress-controller/CHANGELOG.md
- helm/ingress-controller/Chart.yaml
- helm/ingress-controller/tests/__snapshot__/controller-deployment_test.yaml.snap
- helm/ingress-controller/tests/__snapshot__/controller-serviceaccount_test.yaml.snap
- helm/ingress-controller/tests/__snapshot__/ingress-class_test.yaml.snap
Releases version 0.10.0 of the helm-chart. Defaults the controller image version to 0.8.0.
No
> 🎉 Cut Helm chart 0.10.0 release 🎉

- .github/workflows/helm_release.yaml
- .github/workflows/pr-comments.yaml
- Makefile
- helm/ingress-controller/.gitignore
- helm/ingress-controller/Chart.lock
- helm/ingress-controller/Chart.yaml
- helm/ingress-controller/README.md
- helm/ingress-controller/templates/controller-deployment.yaml
- helm/ingress-controller/templates/controller-pdb.yaml
- helm/ingress-controller/tests/__snapshot__/controller-deployment_test.yaml.snap
- helm/ingress-controller/tests/__snapshot__/controller-pdb_test.yaml.snap
- helm/ingress-controller/tests/controller-deployment_test.yaml
- helm/ingress-controller/tests/controller-pdb_test.yaml
- helm/ingress-controller/values.yaml
- scripts/helm-setup.sh
Fixes #254 #255 
* Adds support for configuring pod affinities
* Adds support for creating a pod disruption budget
* Adds support for setting a priorityClassName for the pod
* Adds a dependency on bitnami's common library chart and updates necessary make targets and Github actions to support helm dependencies.
* Add some tests to validate the rendered manifests match what is expected in each case.
No
> More helm features

- e2e-fixtures/hello-https-ingress/EXAMPLE-config.yaml
- e2e-fixtures/hello-world-ingress/EXAMPLE-config-pt2.yaml
- e2e-fixtures/hello-world-ingress/EXAMPLE-config.yaml
- e2e-fixtures/hello-world-namespaced/EXAMPLE-config.yaml
- e2e-fixtures/ingress-class/EXAMPLE-config-different.yaml
- e2e-fixtures/ingress-class/EXAMPLE-config.yaml
- e2e-fixtures/multiple-paths/EXAMPLE-config.yaml
- e2e-fixtures/route-modules/EXAMPLE-config.yaml
- scripts/cleanup-fixtures.sh
- scripts/create-fixtures.sh
- scripts/e2e.sh
- scripts/init_e2e_configs.sh
- scripts/remove-finalizers.sh
* fix the shebangs for nixos users
* split the e2e operations into discrete scripts
* template the full domain so that it's testable with a free account
> some small development script improvements

- docs/deployment-guide/README.md
- scripts/preflight.sh
> update documentation, add preflight check success output

- helm/ingress-controller/Chart.lock
- helm/ingress-controller/README.md
- helm/ingress-controller/templates/controller-deployment.yaml
- helm/ingress-controller/values.yaml
closes: #299
Provides ability to customize [lifecycle](https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#LifecycleHandler) of the controller.
Add `lifecycle` to `values.yaml` and use it in the templates.
None
> Add lifecycle hooks to the template

- README.md
> fix: update readme from main

- helm/ingress-controller/templates/NOTES.txt
> fix: lowercase ngrok in helm NOTES.txt

- .github/ISSUE_TEMPLATE/controller_bug_report.yaml
Closes: #284 
Gives additional context for bugs submitted
Asks for more info
No
> feat: Prompt for additional info in issues template

- e2e-fixtures/route-modules/route-modules.yaml
- helm/ingress-controller/Chart.lock
- internal/controllers/ippolicy_controller.go
I noticed that my ippolicy CRDs don't realize the rules associated with them.
As part of create/update, also reconcile the rules.
None
> Reconcile IP policy rules

- README.md
Add install instructions for gateway preview
> add Gateway instruction to readme

- Makefile
- helm/ingress-controller/Chart.lock
- helm/ingress-controller/tests/__snapshot__/controller-deployment_test.yaml.snap
- helm/ingress-controller/tests/__snapshot__/controller-rbac_test.yaml.snap
- scripts/helm-setup.sh
* Updates the bitnami-common dependency.
* Updates the helm-unittest plugin
No. The bitnami-common dependency doesn't produce any changes in the snapshots. The helm-unittest plugin just changes whitespace in the snapshot files.
> chore: Update helm deps

- internal/store/driver.go
Distinguish between the ingress controller and gateway api in the edge UI with _metadata_
- Split metadata field to ingress and gateway
- Plumb these values to ingress and gateway segments of code
Nope
> set metadata for edges created by the gateway

- cmd/main.go
- go.mod
- pkg/tunneldriver/driver.go
closes: #174
Ideally, we would like to able to start the controller, even if it cannot establish ngrok session right away.
Add session change handlers and evolve the session through connect/disconnects.
None.
> support for async session creation

- go.mod
- go.sum
Pull in latest client.
Needed to send raw json messages.
Update version in go mod
> ngrok client api update

- go.mod
- go.sum
Fixes not all reserved addrs being returned while iterating
Bump ngrok-api-go version to pick up fix
No
> fix: Bump ngrok-api-go version

- internal/controller/ingress/tlsedge_controller.go
Fixes a bug in the TLSEdge controller where changing the hostports in the spec was not triggering an an API call to update the hostports in the API.
* Updating a bunch of log statements so we get more info on the object that triggered the reconcile.
* Add more logging so we can tell what went wrong
* Fix the bug where we were using the hostports from the status field and not the spec.
No
> fix: TLSEdge not reconciling changes to hostports

- docs/examples/external-dns/README.md
Add some documentation about potential issues when using external-dns
> docs: Add note about external-dns policy and dns issues

- docs/CONTRIBUTING.md
- helm/ingress-controller/Chart.lock
Closes #346 
Adds a `CONTRIBUTING.md` file explaining how to contribute.
No
> Add a contributing guide

- internal/controller/ingress/service_controller.go
Fixes #401 
Previously, deleting ngrok LoadBalancer services would hang until the owned resources were manually cleaned up. This is because the sub resource reconciler was not being called to delete the owned resources and would continually re-queue. 
Now, on deletion of the service, if there are owned resources we clean them up first.
No
> fix: Deleting ngrok LoadBalancer services hanging

- .github/workflows/ci.yaml
- Dockerfile
- Makefile
- flake.lock
- flake.nix
- internal/controller/ingress/tcpedge_controller.go
- internal/store/store.go
- scripts/preflight.sh
Updates to to 1.23
Update our nix flake, docker image version used to build, and preflight script check
No
> chore(deps): Update go 1.22 -> 1.23

- .envrc
- .gitignore
- docs/developer-guide/README.md
Minor refresh to help local setup.
* Add support for `.envrc-user`
* Add note to developer guide about loading docker images
> Add support for .envrc-user

- Makefile
- cmd/main.go
- helm/ingress-controller/README.md
- helm/ingress-controller/templates/controller-deployment.yaml
- helm/ingress-controller/tests/__snapshot__/controller-deployment_test.yaml.snap
- helm/ingress-controller/values.yaml
Adds feature flags support (primarily for bindings)
* Support flag: `--enable-feature-bindings`
> Add feature flag support for bindings

- README.md
Caught a few more instances of `ingress controller` in README and changed them to use `ngrok Kubernetes Operator`.
> Update README.md to use ngrok Kubernetes Operator instead of ingress controller. 

- cmd/main.go
- helm/ngrok-operator/CHANGELOG.md
- helm/ngrok-operator/README.md
- helm/ngrok-operator/templates/controller-deployment.yaml
- helm/ngrok-operator/tests/controller-deployment_test.yaml
- helm/ngrok-operator/values.yaml
- internal/store/driver.go
Part-of: https://github.com/ngrok-private/ngrok/issues/33171
Standardize on `ngrokMetadata` for clarity
* Rename .Values.metaData -> .Values.ngrokMetadata
* Standardize on ngrokMetadata
* Update CHANGELOG.md
> Rename .Values.metaData -> .Values.ngrokMetadata

- helm/ngrok-operator/templates/rbac/bindingconfiguration_editor_role.yaml
- helm/ngrok-operator/templates/rbac/bindingconfiguration_viewer_role.yaml
- helm/ngrok-operator/templates/rbac/endpointbinding_editor_role.yaml
- helm/ngrok-operator/templates/rbac/endpointbinding_viewer_role.yaml
- helm/ngrok-operator/templates/rbac/operatorconfiguration_editor_role.yaml
- helm/ngrok-operator/templates/rbac/operatorconfiguration_viewer_role.yaml
- helm/ngrok-operator/templates/rbac/role.yaml
- helm/ngrok-operator/tests/__snapshot__/controller-deployment_test.yaml.snap
- internal/controller/ngrok/operatorconfiguration.go
* Add missing kubebuilder rbac annotations
* Add missing rbac templates
Copy/Paste from existing examples
> Add missing rbac

- Makefile
- api/bindings/v1alpha1/bindingconfiguration_types.go
- helm/ngrok-operator/README.md
- helm/ngrok-operator/templates/binding-configuration.yaml
- helm/ngrok-operator/templates/crds/bindings.k8s.ngrok.com_bindingconfigurations.yaml
- helm/ngrok-operator/tests/__snapshot__/binding-configuration_test.yaml.snap
- helm/ngrok-operator/tests/binding-configuration_test.yaml
- helm/ngrok-operator/values.yaml
Closes: https://github.com/ngrok-private/ngrok/issues/33171
Adds in an initial implementation of `kind: BindingConfiguration` which is the base of the bindings feature.
* Add needed fields
* Update print columns
* Upadate Helm chart/values
> Add BindingConfiguration scaffolding implementation

- cmd/main.go
- internal/healthcheck/healthcheck.go
- internal/healthcheck/healthcheck_test.go
- pkg/tunneldriver/driver.go
Implement a new healthchecker package that will enable us to better split up the responsibilities of each ngrok-op feature set.
Implement a naive and simple healthcheck pkg
* Add internal/healthcheck
* Implement the healthcheck.HealthChecker interface
```
ok  	github.com/ngrok/ngrok-operator/internal/healthcheck	1.254s	coverage: 100.0% of statements
```
Nice.
> Add internal/healthcheck

- cmd/main.go
- helm/ngrok-operator/templates/controller-deployment.yaml
Separate the feature sets into different functions and options.
* Add feature flags for ingress and gateway
* Split up featureset registration in main.go
> Separate featuresets

- cmd/main.go
- internal/controller/bindings/bindingconfiguration_controller.go
- internal/controller/bindings/endpointbinding_poller.go
Mock out calls to our API and wire up the polling loop to call it and update CRDs
- We want to poll the ngrok API for endpoints that have been bound and then create CRDs from their config. 
- The apis are still being worked on so this mocks out the response of the URL field
- This creates a runnable interface that can be added to the manager
- it's all mock fake data, but its behind the bindings feature flag. 
> Create a runnable that polls the api and creates crds using a mock api for now

- api/bindings/v1alpha1/bindingconfiguration_types.go
- api/bindings/v1alpha1/endpointbinding_types.go
- helm/ngrok-operator/templates/crds/bindings.k8s.ngrok.com_endpointbindings.yaml
- internal/ngrokapi/bindingendpoint_aggregator.go
- internal/ngrokapi/bindingendpoint_aggregator_test.go
`AggregateBindingEndpoints` turns multiple `binding_endpoints` into a map of `hostport -> EndpointBinding`.
This is the abstraction to handle the Many-to-One relationship from Endpoint -> Service (as represented by `kind: EndpointBinding` in our operator).
No
> Implement AggregateBindingEndpoints for interacting with the ngrok api

- .github/labeler.yml
- .golangci.yml
- internal/ngrokapi/bindingendpoint_aggregator.go
- internal/ngrokapi/bindingendpoint_aggregator_test.go
Makes sure code is `gofmt`'d properly.
Enable the linter in golangci-lint configuration. First commit will fail CI as a test, then we'll push it after its been formatted and it should succeed.
No.
> feat(ci): Add gofmt to lints

- api/bindings/v1alpha1/endpointbinding_types.go
- cmd/api/main.go
- helm/ngrok-operator/templates/crds/bindings.k8s.ngrok.com_endpointbindings.yaml
- internal/controller/bindings/endpointbinding_poller.go
- internal/controller/bindings/endpointbinding_poller_test.go
Implement the full scaffolding (mocked) for the EndpointBinding poller loop
* Update EndpointBindingPoller with new mocked data
* Update kubectl output for EndpointBinding
* Add tests for updates
* Implement EndpointBinding status
No
> Implement BindingEndpoint polling

- api/bindings/v1alpha1/endpointbinding_types.go
- cmd/api/main.go
- go.mod
- helm/ngrok-operator/templates/rbac/role.yaml
- helm/ngrok-operator/tests/__snapshot__/controller-deployment_test.yaml.snap
- internal/controller/base_controller.go
- internal/controller/bindings/endpointbinding_controller.go
- internal/controller/bindings/endpointbinding_controller_test.go
- internal/controller/bindings/endpointbinding_poller.go
- internal/controller/bindings/endpointbinding_poller_test.go
- internal/ngrokapi/bindingendpoint_aggregator.go
- internal/ngrokapi/bindingendpoint_aggregator_test.go
- internal/util/maps.go
- internal/util/maps_test.go
Implement the reconciliation of EndpointBinding -> Service (Target and Upstream)
* Implement EndpointBinding -> Services creation
* Implement EndpointBinding reconciler
* Implement target metadata
* Implement Target and Upstream Service reconciliation
* Use correct EventRecording types
No.
> Implement EndpointBinding -> Services creation

- api/bindings/v1alpha1/endpointbinding_types.go
- cmd/api/main.go
- go.mod
- go.sum
- helm/ngrok-operator/templates/crds/bindings.k8s.ngrok.com_endpointbindings.yaml
- internal/controller/bindings/endpointbinding_controller.go
- internal/controller/bindings/endpointbinding_controller_test.go
- internal/controller/bindings/endpointbinding_poller.go
- internal/controller/bindings/port_allocator.go
- internal/controller/bindings/port_allocator_test.go
Implement port allocation for EndpointBindings
Use a port bitmap (from ngrok internal monorepo)
Use a static allocation strategy (noted in comments)
Use a fixed port range from 10000-65535 allowing for ~50k EndpointBindings :see_no_evil:
> Implement port allocation

- internal/controller/base_controller.go
- internal/controller/bindings/endpointbinding_controller.go
- internal/controller/bindings/endpointbinding_controller_test.go
- internal/controller/bindings/endpointbinding_poller.go
- internal/controller/bindings/endpointbinding_poller_test.go
- internal/controller/gateway/gateway_controller.go
- internal/controller/gateway/httproute_controller.go
- internal/controller/ingress/httpsedge_controller.go
- internal/controller/ingress/ingress_controller.go
- internal/controller/ingress/ippolicy_controller.go
- internal/controller/ingress/service_controller.go
- internal/controller/ingress/tcpedge_controller.go
- internal/controller/ingress/tlsedge_controller.go
- internal/controller/ngrok/kubernetesoperator_controller.go
> Standardize logging pattern using ctrl.LoggerFrom(ctx)

- api/bindings/v1alpha1/endpointbinding_types.go
- helm/ngrok-operator/templates/crds/bindings.k8s.ngrok.com_endpointbindings.yaml
- internal/controller/bindings/endpointbinding_controller.go
- internal/controller/bindings/endpointbinding_controller_test.go
- internal/controller/bindings/endpointbinding_poller.go
* Add endpoint status to EndpointBinding kubectl output
* Implement EndpointBinding statuses and dial attempts
* Statuses are updated as best effort after upstream/target service creation
* Target service is attempted to be bound in a background loop
* ngrok errors are mocked for now
* ngrok client is still mocked
No.
> Add endpoint status to EndpointBinding kubectl output

- api/bindings/v1alpha1/endpointbinding_types.go
- api/ngrok/v1alpha1/kubernetesoperator_types.go
- helm/ngrok-operator/templates/crds/bindings.k8s.ngrok.com_endpointbindings.yaml
- helm/ngrok-operator/templates/crds/ngrok.k8s.ngrok.com_kubernetesoperators.yaml
- internal/controller/base_controller.go
- internal/controller/bindings/endpointbinding_controller.go
- internal/controller/ngrok/kubernetesoperator_controller.go
Update status fields
Add basic registration status handling to KubernetesOperator
Use similar pattern to #464
No.
> Add status to KubernetesOperator

- api/bindings/v1alpha1/endpointbinding_types.go
- api/ngrok/v1alpha1/kubernetesoperator_types.go
- helm/ngrok-operator/templates/crds/bindings.k8s.ngrok.com_endpointbindings.yaml
- helm/ngrok-operator/templates/crds/ngrok.k8s.ngrok.com_kubernetesoperators.yaml
- internal/controller/base_controller.go
Fix `errors.As()` casting with `*ngrok.Error` with different versions of `ngrok-go-api` imported :/
Use correct `ngrok-go-api/v6` in base controller
No.
> Use correct import to fix status updates

- internal/controller/ngrok/kubernetesoperator_controller.go
Ensure EnabledFeatures is set from the API
No.
> Ensure KubernetesOperator.Status.EnabledFeatures is set properly from the API

- internal/controller/bindings/boundendpoint_poller.go
- internal/controller/bindings/boundendpoint_poller_test.go
`reflect.DeepEqual()` treats `nil` vs. `map[string]string{}` as unequal (rightfully so!)
But our k8s types for `TargetMetadata` doesn't consider those different.
I created a new equality function to test the target metadata equality directly
No.
> Add equality tests for Target.Metadata

- internal/controller/ngrok/kubernetesoperator_controller.go
Fixes a panic when bindings is not enabled.
```
{"level":"info","ts":"2024-11-01T17:23:25Z","msg":"Observed a panic in reconciler: runtime error: invalid memory address or nil pointer dereference","controller":"kubernetesoperator","controllerGroup":"ngrok.k8s.ngrok.com","controllerKind":"KubernetesOperator","KubernetesOperator":{"name":"ngrok-operator","namespace":"ngrok-operator"},"namespace":"ngrok-operator","name":"ngrok-operator","reconcileID":"484ebbf8-f601-41b2-8c15-dd5b6f5cd924"}
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x110 pc=0x16a41d8]
goroutine 430 [running]: …
```
> fix: Add nil checks to prevent potential panics

- internal/controller/ngrok/kubernetesoperator_controller.go
While fixing the panics that we were getting, I introduced a bug in https://github.com/ngrok/ngrok-operator/pull/483 that would only update the status if bindings was enabled. We should update the status either way.
Don't return nil, make sure we update the status. Also, we clearing the Status.ID on all errors. We probably don't want to do this in the case of network errors, so only explicitly clear the ID and URI on not found errors.
No
> fix: Make sure we update the status

- internal/mux/header.go
Add logging to help with future debugging
> Add more logging for binding forwarder mux handshake

- internal/controller/ingress/ingress_controller.go
Fix panic noted here https://github.com/ngrok/ngrok-operator/issues/428#issuecomment-2466780489
Last minute I changed to use events instead of logs and didn't think about how the ingress object for the recorder would be nil in the case of an error
This updates to use the previously gotten ingress object after its error checks, avoiding the issue of potentially using the nil ingress from the update function
> default          4m5s        Warning   InvalidIngressSpec   ingress/chess-bot-ngrok                        Ingress is not valid so skipping it: invalid ingress spec: [A host is required to be set for each rule]
> Use the previously ingress in the error messages

- .github/workflows/helm_release.yaml
- Makefile
- docs/developer-guide/releasing.md
- scripts/release.sh
Configure Helm chart releasing for ngrok/helm-charts repo
Add release.sh automation
Update the github workflows
Add new script `release.sh`
* create new release branch from main
* discover PRs since last release
* insert/update/edit the changelogs
* commit and review changes
No.
> Automate releases

- helm/ngrok-operator/templates/NOTES.txt
Update NOTES.txt on Helm install
With my text editor
No.
> Update NOTES.txt for new feature sets

- scripts/release.sh
> Update the gather PR logic for release.sh

- scripts/release.sh
> Update messaging for release changelogs

- .github/workflows/helm_release.yaml
Add gpg signing steps to the helm-releaser-action for the ngrok-operator Helm chart 
> Add gpg Helm chart signing

- README.md
> Update README.md with new rename

- .github/workflows/helm_release.yaml
> Update gpg key id

- .github/workflows/helm_release.yaml
> Use the key name instead of the ID

- helm/ngrok-operator/README.md
> Update the helm README.md for rename

- README.md
> Add artifacthub badge

- pkg/tunneldriver/driver.go
When changing the appProtocol or forwardsTo on a tunnel, it isn't being re-created. This leads to incorrect behavior and  possibly breaking changes when the operator restarts.
If the appProtocol or forwardsTo changes for a tunnel, we should re-create it.
No
> fix: Re-create tunnel if forwardsTo or appProto changes

- .github/workflows/ci.yaml
- .github/workflows/test.yaml
- Makefile
Testing e2e and trying to get it to work. A challenge here is that `pull_request_target` is only taken from `main` so we need to merge PRs to test changes.
* Remove `echo` job (whoops)
* Change name of `build-and-test-e2e` for `test.yaml`
* Remove `pull_request_target` for `ci.yaml`
> e2e updates / fixes 1

- .github/actions/build-and-test/action.yaml
> Use correct namespace for debugging

- .github/workflows/ci.yaml
- .github/workflows/test.yaml
> Ensure build-and-test runs on push events

- .github/actions/changes/action.yaml
> Fix typo for changes to tests ; Add scripts/e2e.sh too

- .github/workflows/test.yaml
Spoke with Stacks about how we can enable forks' PRs to test code using secrets within the ngrok/ngrok-operator repo.
Directly checkout PR HEAD
> Checkout fork PR HEAD for e2e tests

- .github/workflows/test.yaml
> Enable deny gate for 'safe to test' label

- helm/ngrok-operator/templates/NOTES.txt
With the recent changes to the bindings api the post-install text references things that no longer exist.
Updates the text to accurately reflect the state of bindings!
None!
> update notes.txt to reflect bindings api changes

- .golangci.yml
- internal/annotations/parser/parser.go
- internal/annotations/webhook_verification/webhook_verification.go
- internal/controller/base_controller.go
- internal/controller/gateway/gateway_controller.go
- internal/controller/gateway/httproute_controller.go
- internal/controller/ingress/service_controller.go
- internal/ir/ir.go
- internal/ngrokapi/bindingendpoint_aggregator.go
- pkg/managerdriver/tunnels.go
Catch potential bugs and styling issues
* Enable go-critic in the golang-ci linters
No
> chore(lint): Enable go-critic

- internal/controller/agent/agent_endpoint_controller.go
Discovered while testing #612. The new mapping strategy will take existing LB services with a cloud endpoint & agent endpoint and convert them to just an agent endpoint. In this case, the domain will already exist.
Fixes a bug where the agent endpoint wouldn't reconcile if the domain CRD already exists. This was caused by a bad conditional that was returning `nil` when there was an error getting the domain and not handling the case where the `err == nil`. In the `err == nil` case(A domain already exists), we were still trying to create the domain.
If the domain already exists, but we don't have a Status ID for it(It hasn't been reconciled with the ngrok API yet), return an error that the domain is creating. Otherwise, return an error except if the domain is not found. Only then will we …
> fix: Agent endpoint domain strategy

- helm/ngrok-operator/CHANGELOG.md
- helm/ngrok-operator/Chart.yaml
- helm/ngrok-operator/tests/__snapshot__/controller-deployment_test.yaml.snap
- helm/ngrok-operator/tests/__snapshot__/controller-pdb_test.yaml.snap
- helm/ngrok-operator/tests/__snapshot__/controller-serviceaccount_test.yaml.snap
- helm/ngrok-operator/tests/__snapshot__/ingress-class_test.yaml.snap
- helm/ngrok-operator/tests/agent/__snapshot__/deployment_test.yaml.snap
- helm/ngrok-operator/tests/agent/__snapshot__/service-account_test.yaml.snap
- helm/ngrok-operator/tests/bindings-forwarder/__snapshot__/deployment_test.yaml.snap
- helm/ngrok-operator/tests/bindings-forwarder/__snapshot__/service-account_test.yaml.snap
Release helm-chart `0.18.0`
Promotes development release `0.18.0-rc.1` to `0.18.0`
No
> :tada: Release helm chart 0.18.0 :tada:

- .github/workflows/helm_release.yaml
Upload charts to charts.ngrok.com on release
For each of the charts we packaged in `./.cr-release-packages`, upload them to `charts.ngrok.com`
No
> feat: Upload charts to charts.ngrok.com

- Dockerfile
- cmd/agent-manager.go
- cmd/api-manager.go
- cmd/bindings-forwarder-manager.go
- cmd/root.go
- helm/ngrok-operator/templates/agent/deployment.yaml
- helm/ngrok-operator/templates/bindings-forwarder/deployment.yaml
- helm/ngrok-operator/templates/controller-deployment.yaml
- helm/ngrok-operator/tests/__snapshot__/controller-deployment_test.yaml.snap
- helm/ngrok-operator/tests/agent/__snapshot__/deployment_test.yaml.snap
- helm/ngrok-operator/tests/bindings-forwarder/__snapshot__/deployment_test.yaml.snap
- main.go
- tools/make/build.mk
Contributes to #478 
Combine three individual binaries into a single binary with three subcommands
Image size comparison:
make a new top-level `main.go` which executes a new root cobra command and then register each of the previously separate cobra apps as subcommands off the new root command.
Does change the template for deployments
Just sanity checking that the operator pods come up and run as we expect (here's the bindings-forwarder pod running with the new command structure as an example, but all three are ready/running and free of error logs)
> Combine binaries

- internal/store/store.go
While working on the gateway status work. I needed to add the GatewayClass to the cache stores. While doing that I noticed we had a lot of the same code.
* Add `GetGatewayClass()` and `ListGatewayClasses()` to the Storer interface
* Refactors the Get and List methods to clean up some code.
No
> Add gatewayclass to store

- helm/ngrok-operator/templates/NOTES.txt
My suggestions for updates to the helm notes which are out of date and include wrong docs links.
Examples with the mentioned features enabled/disabled.
> update helm notes

- .github/workflows/generate-chart-readme.yaml
Update the readme generator workflow
No
> chore: update readme-generator workflow
